/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { CxxPositionWire } from '../ark-cxx-ast-fb/cxx-position-wire';


export class CxxRangeWire {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):CxxRangeWire {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsCxxRangeWire(bb:flatbuffers.ByteBuffer, obj?:CxxRangeWire):CxxRangeWire {
  return (obj || new CxxRangeWire()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsCxxRangeWire(bb:flatbuffers.ByteBuffer, obj?:CxxRangeWire):CxxRangeWire {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new CxxRangeWire()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

begin(obj?:CxxPositionWire):CxxPositionWire|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new CxxPositionWire()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

end(obj?:CxxPositionWire):CxxPositionWire|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new CxxPositionWire()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

spellingLoc(obj?:CxxPositionWire):CxxPositionWire|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new CxxPositionWire()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

expansionLoc(obj?:CxxPositionWire):CxxPositionWire|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new CxxPositionWire()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startCxxRangeWire(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addBegin(builder:flatbuffers.Builder, beginOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, beginOffset, 0);
}

static addEnd(builder:flatbuffers.Builder, endOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, endOffset, 0);
}

static addSpellingLoc(builder:flatbuffers.Builder, spellingLocOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, spellingLocOffset, 0);
}

static addExpansionLoc(builder:flatbuffers.Builder, expansionLocOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, expansionLocOffset, 0);
}

static endCxxRangeWire(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
