/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class CxxPositionWire {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):CxxPositionWire {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsCxxPositionWire(bb:flatbuffers.ByteBuffer, obj?:CxxPositionWire):CxxPositionWire {
  return (obj || new CxxPositionWire()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsCxxPositionWire(bb:flatbuffers.ByteBuffer, obj?:CxxPositionWire):CxxPositionWire {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new CxxPositionWire()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

line():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

col():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

offset():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

tokLen():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

file():string|null
file(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
file(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startCxxPositionWire(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addLine(builder:flatbuffers.Builder, line:number) {
  builder.addFieldInt32(0, line, 0);
}

static addCol(builder:flatbuffers.Builder, col:number) {
  builder.addFieldInt32(1, col, 0);
}

static addOffset(builder:flatbuffers.Builder, offset:number) {
  builder.addFieldInt32(2, offset, 0);
}

static addTokLen(builder:flatbuffers.Builder, tokLen:number) {
  builder.addFieldInt32(3, tokLen, 0);
}

static addFile(builder:flatbuffers.Builder, fileOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, fileOffset, 0);
}

static endCxxPositionWire(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createCxxPositionWire(builder:flatbuffers.Builder, line:number, col:number, offset:number, tokLen:number, fileOffset:flatbuffers.Offset):flatbuffers.Offset {
  CxxPositionWire.startCxxPositionWire(builder);
  CxxPositionWire.addLine(builder, line);
  CxxPositionWire.addCol(builder, col);
  CxxPositionWire.addOffset(builder, offset);
  CxxPositionWire.addTokLen(builder, tokLen);
  CxxPositionWire.addFile(builder, fileOffset);
  return CxxPositionWire.endCxxPositionWire(builder);
}
}
