/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { CxxPositionWire } from '../ark-cxx-ast-fb/cxx-position-wire';


export class CxxIncludeInfoWire {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):CxxIncludeInfoWire {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsCxxIncludeInfoWire(bb:flatbuffers.ByteBuffer, obj?:CxxIncludeInfoWire):CxxIncludeInfoWire {
  return (obj || new CxxIncludeInfoWire()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsCxxIncludeInfoWire(bb:flatbuffers.ByteBuffer, obj?:CxxIncludeInfoWire):CxxIncludeInfoWire {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new CxxIncludeInfoWire()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

code():string|null
code(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
code(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

fileName():string|null
fileName(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
fileName(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

includeName():string|null
includeName(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
includeName(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

includedFrom():string|null
includedFrom(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
includedFrom(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

isAngled():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

kind():string|null
kind(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
kind(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

loc(obj?:CxxPositionWire):CxxPositionWire|null {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? (obj || new CxxPositionWire()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

relativePath():string|null
relativePath(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
relativePath(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

searchPath():string|null
searchPath(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
searchPath(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startCxxIncludeInfoWire(builder:flatbuffers.Builder) {
  builder.startObject(9);
}

static addCode(builder:flatbuffers.Builder, codeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, codeOffset, 0);
}

static addFileName(builder:flatbuffers.Builder, fileNameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, fileNameOffset, 0);
}

static addIncludeName(builder:flatbuffers.Builder, includeNameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, includeNameOffset, 0);
}

static addIncludedFrom(builder:flatbuffers.Builder, includedFromOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, includedFromOffset, 0);
}

static addIsAngled(builder:flatbuffers.Builder, isAngled:boolean) {
  builder.addFieldInt8(4, +isAngled, +false);
}

static addKind(builder:flatbuffers.Builder, kindOffset:flatbuffers.Offset) {
  builder.addFieldOffset(5, kindOffset, 0);
}

static addLoc(builder:flatbuffers.Builder, locOffset:flatbuffers.Offset) {
  builder.addFieldOffset(6, locOffset, 0);
}

static addRelativePath(builder:flatbuffers.Builder, relativePathOffset:flatbuffers.Offset) {
  builder.addFieldOffset(7, relativePathOffset, 0);
}

static addSearchPath(builder:flatbuffers.Builder, searchPathOffset:flatbuffers.Offset) {
  builder.addFieldOffset(8, searchPathOffset, 0);
}

static endCxxIncludeInfoWire(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
