/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { ClassBaseWire } from '../ark-cxx-ast-fb/class-base-wire';
import { CxxCtorAnyInitWire } from '../ark-cxx-ast-fb/cxx-ctor-any-init-wire';
import { CxxEnclosingFunctionWire } from '../ark-cxx-ast-fb/cxx-enclosing-function-wire';
import { CxxIncludeInfoWire } from '../ark-cxx-ast-fb/cxx-include-info-wire';
import { CxxLocWire } from '../ark-cxx-ast-fb/cxx-loc-wire';
import { CxxNominatedNamespaceWire } from '../ark-cxx-ast-fb/cxx-nominated-namespace-wire';
import { CxxRangeWire } from '../ark-cxx-ast-fb/cxx-range-wire';
import { CxxReferencedDeclWire } from '../ark-cxx-ast-fb/cxx-referenced-decl-wire';
import { CxxTypeInfoWire } from '../ark-cxx-ast-fb/cxx-type-info-wire';
import { DefaultArgWire } from '../ark-cxx-ast-fb/default-arg-wire';
import { DtorTypeWire } from '../ark-cxx-ast-fb/dtor-type-wire';


/**
 * Per-node attrs as structured columns (inner/header_units are separate wire vectors).
 */
export class CxxAstNodeWire {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):CxxAstNodeWire {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsCxxAstNodeWire(bb:flatbuffers.ByteBuffer, obj?:CxxAstNodeWire):CxxAstNodeWire {
  return (obj || new CxxAstNodeWire()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsCxxAstNodeWire(bb:flatbuffers.ByteBuffer, obj?:CxxAstNodeWire):CxxAstNodeWire {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new CxxAstNodeWire()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

id():string|null
id(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
id(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

originalId():string|null
originalId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
originalId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

hasInClassInitializer():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

kind():string|null
kind(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
kind(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

code():string|null
code(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
code(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

type(obj?:CxxTypeInfoWire):CxxTypeInfoWire|null {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? (obj || new CxxTypeInfoWire()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

mangledName():string|null
mangledName(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
mangledName(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

tagUsed():string|null
tagUsed(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
tagUsed(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

isImplicit():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

storageClass():string|null
storageClass(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
storageClass(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 24);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

access():string|null
access(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
access(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 26);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

referencedDecl(obj?:CxxReferencedDeclWire):CxxReferencedDeclWire|null {
  const offset = this.bb!.__offset(this.bb_pos, 28);
  return offset ? (obj || new CxxReferencedDeclWire()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

value():string|null
value(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
value(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 30);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

valueCategory():string|null
valueCategory(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
valueCategory(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 32);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

castKind():string|null
castKind(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
castKind(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 34);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

opcode():string|null
opcode(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
opcode(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 36);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

op():string|null
op(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
op(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 38);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

isPostfix():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 40);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

isArrow():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 42);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

isArray():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 44);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

traitFunc():string|null
traitFunc(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
traitFunc(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 46);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

traitArgs():string|null
traitArgs(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
traitArgs(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 48);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

noexceptArg():string|null
noexceptArg(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
noexceptArg(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 50);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

typeArg(obj?:CxxTypeInfoWire):CxxTypeInfoWire|null {
  const offset = this.bb!.__offset(this.bb_pos, 52);
  return offset ? (obj || new CxxTypeInfoWire()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

atomicFunc():string|null
atomicFunc(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
atomicFunc(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 54);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

pseudoDestructorType():string|null
pseudoDestructorType(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
pseudoDestructorType(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 56);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

targetLabelId():number {
  const offset = this.bb!.__offset(this.bb_pos, 58);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

anyInit(obj?:CxxCtorAnyInitWire):CxxCtorAnyInitWire|null {
  const offset = this.bb!.__offset(this.bb_pos, 60);
  return offset ? (obj || new CxxCtorAnyInitWire()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

baseInit(obj?:CxxTypeInfoWire):CxxTypeInfoWire|null {
  const offset = this.bb!.__offset(this.bb_pos, 62);
  return offset ? (obj || new CxxTypeInfoWire()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

nominatedNamespace(obj?:CxxNominatedNamespaceWire):CxxNominatedNamespaceWire|null {
  const offset = this.bb!.__offset(this.bb_pos, 64);
  return offset ? (obj || new CxxNominatedNamespaceWire()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

loc(obj?:CxxLocWire):CxxLocWire|null {
  const offset = this.bb!.__offset(this.bb_pos, 66);
  return offset ? (obj || new CxxLocWire()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

range(obj?:CxxRangeWire):CxxRangeWire|null {
  const offset = this.bb!.__offset(this.bb_pos, 68);
  return offset ? (obj || new CxxRangeWire()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

enclosingFunction(obj?:CxxEnclosingFunctionWire):CxxEnclosingFunctionWire|null {
  const offset = this.bb!.__offset(this.bb_pos, 70);
  return offset ? (obj || new CxxEnclosingFunctionWire()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

defaultArg(obj?:DefaultArgWire):DefaultArgWire|null {
  const offset = this.bb!.__offset(this.bb_pos, 72);
  return offset ? (obj || new DefaultArgWire()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

dtor(obj?:DtorTypeWire):DtorTypeWire|null {
  const offset = this.bb!.__offset(this.bb_pos, 74);
  return offset ? (obj || new DtorTypeWire()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

default_():string|null
default_(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
default_(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 76);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

arraySizes(index: number):string
arraySizes(index: number,optionalEncoding:flatbuffers.Encoding):string|Uint8Array
arraySizes(index: number,optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 78);
  return offset ? this.bb!.__string(this.bb!.__vector(this.bb_pos + offset) + index * 4, optionalEncoding) : null;
}

arraySizesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 78);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

typeArguments(index: number):string
typeArguments(index: number,optionalEncoding:flatbuffers.Encoding):string|Uint8Array
typeArguments(index: number,optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 80);
  return offset ? this.bb!.__string(this.bb!.__vector(this.bb_pos + offset) + index * 4, optionalEncoding) : null;
}

typeArgumentsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 80);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

includes(index: number, obj?:CxxIncludeInfoWire):CxxIncludeInfoWire|null {
  const offset = this.bb!.__offset(this.bb_pos, 82);
  return offset ? (obj || new CxxIncludeInfoWire()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

includesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 82);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

bases(index: number, obj?:ClassBaseWire):ClassBaseWire|null {
  const offset = this.bb!.__offset(this.bb_pos, 84);
  return offset ? (obj || new ClassBaseWire()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

basesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 84);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

inner(index: number, obj?:CxxAstNodeWire):CxxAstNodeWire|null {
  const offset = this.bb!.__offset(this.bb_pos, 86);
  return offset ? (obj || new CxxAstNodeWire()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

innerLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 86);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

headerUnits(index: number, obj?:CxxAstNodeWire):CxxAstNodeWire|null {
  const offset = this.bb!.__offset(this.bb_pos, 88);
  return offset ? (obj || new CxxAstNodeWire()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

headerUnitsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 88);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startCxxAstNodeWire(builder:flatbuffers.Builder) {
  builder.startObject(43);
}

static addId(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, idOffset, 0);
}

static addOriginalId(builder:flatbuffers.Builder, originalIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, originalIdOffset, 0);
}

static addHasInClassInitializer(builder:flatbuffers.Builder, hasInClassInitializer:boolean) {
  builder.addFieldInt8(2, +hasInClassInitializer, +false);
}

static addKind(builder:flatbuffers.Builder, kindOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, kindOffset, 0);
}

static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, nameOffset, 0);
}

static addCode(builder:flatbuffers.Builder, codeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(5, codeOffset, 0);
}

static addType(builder:flatbuffers.Builder, typeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(6, typeOffset, 0);
}

static addMangledName(builder:flatbuffers.Builder, mangledNameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(7, mangledNameOffset, 0);
}

static addTagUsed(builder:flatbuffers.Builder, tagUsedOffset:flatbuffers.Offset) {
  builder.addFieldOffset(8, tagUsedOffset, 0);
}

static addIsImplicit(builder:flatbuffers.Builder, isImplicit:boolean) {
  builder.addFieldInt8(9, +isImplicit, +false);
}

static addStorageClass(builder:flatbuffers.Builder, storageClassOffset:flatbuffers.Offset) {
  builder.addFieldOffset(10, storageClassOffset, 0);
}

static addAccess(builder:flatbuffers.Builder, accessOffset:flatbuffers.Offset) {
  builder.addFieldOffset(11, accessOffset, 0);
}

static addReferencedDecl(builder:flatbuffers.Builder, referencedDeclOffset:flatbuffers.Offset) {
  builder.addFieldOffset(12, referencedDeclOffset, 0);
}

static addValue(builder:flatbuffers.Builder, valueOffset:flatbuffers.Offset) {
  builder.addFieldOffset(13, valueOffset, 0);
}

static addValueCategory(builder:flatbuffers.Builder, valueCategoryOffset:flatbuffers.Offset) {
  builder.addFieldOffset(14, valueCategoryOffset, 0);
}

static addCastKind(builder:flatbuffers.Builder, castKindOffset:flatbuffers.Offset) {
  builder.addFieldOffset(15, castKindOffset, 0);
}

static addOpcode(builder:flatbuffers.Builder, opcodeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(16, opcodeOffset, 0);
}

static addOp(builder:flatbuffers.Builder, opOffset:flatbuffers.Offset) {
  builder.addFieldOffset(17, opOffset, 0);
}

static addIsPostfix(builder:flatbuffers.Builder, isPostfix:boolean) {
  builder.addFieldInt8(18, +isPostfix, +false);
}

static addIsArrow(builder:flatbuffers.Builder, isArrow:boolean) {
  builder.addFieldInt8(19, +isArrow, +false);
}

static addIsArray(builder:flatbuffers.Builder, isArray:boolean) {
  builder.addFieldInt8(20, +isArray, +false);
}

static addTraitFunc(builder:flatbuffers.Builder, traitFuncOffset:flatbuffers.Offset) {
  builder.addFieldOffset(21, traitFuncOffset, 0);
}

static addTraitArgs(builder:flatbuffers.Builder, traitArgsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(22, traitArgsOffset, 0);
}

static addNoexceptArg(builder:flatbuffers.Builder, noexceptArgOffset:flatbuffers.Offset) {
  builder.addFieldOffset(23, noexceptArgOffset, 0);
}

static addTypeArg(builder:flatbuffers.Builder, typeArgOffset:flatbuffers.Offset) {
  builder.addFieldOffset(24, typeArgOffset, 0);
}

static addAtomicFunc(builder:flatbuffers.Builder, atomicFuncOffset:flatbuffers.Offset) {
  builder.addFieldOffset(25, atomicFuncOffset, 0);
}

static addPseudoDestructorType(builder:flatbuffers.Builder, pseudoDestructorTypeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(26, pseudoDestructorTypeOffset, 0);
}

static addTargetLabelId(builder:flatbuffers.Builder, targetLabelId:number) {
  builder.addFieldInt32(27, targetLabelId, 0);
}

static addAnyInit(builder:flatbuffers.Builder, anyInitOffset:flatbuffers.Offset) {
  builder.addFieldOffset(28, anyInitOffset, 0);
}

static addBaseInit(builder:flatbuffers.Builder, baseInitOffset:flatbuffers.Offset) {
  builder.addFieldOffset(29, baseInitOffset, 0);
}

static addNominatedNamespace(builder:flatbuffers.Builder, nominatedNamespaceOffset:flatbuffers.Offset) {
  builder.addFieldOffset(30, nominatedNamespaceOffset, 0);
}

static addLoc(builder:flatbuffers.Builder, locOffset:flatbuffers.Offset) {
  builder.addFieldOffset(31, locOffset, 0);
}

static addRange(builder:flatbuffers.Builder, rangeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(32, rangeOffset, 0);
}

static addEnclosingFunction(builder:flatbuffers.Builder, enclosingFunctionOffset:flatbuffers.Offset) {
  builder.addFieldOffset(33, enclosingFunctionOffset, 0);
}

static addDefaultArg(builder:flatbuffers.Builder, defaultArgOffset:flatbuffers.Offset) {
  builder.addFieldOffset(34, defaultArgOffset, 0);
}

static addDtor(builder:flatbuffers.Builder, dtorOffset:flatbuffers.Offset) {
  builder.addFieldOffset(35, dtorOffset, 0);
}

static addDefault(builder:flatbuffers.Builder, default_Offset:flatbuffers.Offset) {
  builder.addFieldOffset(36, default_Offset, 0);
}

static addArraySizes(builder:flatbuffers.Builder, arraySizesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(37, arraySizesOffset, 0);
}

static createArraySizesVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startArraySizesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addTypeArguments(builder:flatbuffers.Builder, typeArgumentsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(38, typeArgumentsOffset, 0);
}

static createTypeArgumentsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startTypeArgumentsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addIncludes(builder:flatbuffers.Builder, includesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(39, includesOffset, 0);
}

static createIncludesVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startIncludesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addBases(builder:flatbuffers.Builder, basesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(40, basesOffset, 0);
}

static createBasesVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startBasesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addInner(builder:flatbuffers.Builder, innerOffset:flatbuffers.Offset) {
  builder.addFieldOffset(41, innerOffset, 0);
}

static createInnerVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startInnerVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addHeaderUnits(builder:flatbuffers.Builder, headerUnitsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(42, headerUnitsOffset, 0);
}

static createHeaderUnitsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startHeaderUnitsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endCxxAstNodeWire(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
