/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { CxxAliasInfoWire } from '../ark-cxx-ast-fb/cxx-alias-info-wire';
import { CxxTypeInfoWire } from '../ark-cxx-ast-fb/cxx-type-info-wire';


export class CxxReferencedDeclWire {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):CxxReferencedDeclWire {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsCxxReferencedDeclWire(bb:flatbuffers.ByteBuffer, obj?:CxxReferencedDeclWire):CxxReferencedDeclWire {
  return (obj || new CxxReferencedDeclWire()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsCxxReferencedDeclWire(bb:flatbuffers.ByteBuffer, obj?:CxxReferencedDeclWire):CxxReferencedDeclWire {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new CxxReferencedDeclWire()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

kind():string|null
kind(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
kind(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

type(obj?:CxxTypeInfoWire):CxxTypeInfoWire|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new CxxTypeInfoWire()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

alias(obj?:CxxAliasInfoWire):CxxAliasInfoWire|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new CxxAliasInfoWire()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startCxxReferencedDeclWire(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addKind(builder:flatbuffers.Builder, kindOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, kindOffset, 0);
}

static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, nameOffset, 0);
}

static addType(builder:flatbuffers.Builder, typeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, typeOffset, 0);
}

static addAlias(builder:flatbuffers.Builder, aliasOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, aliasOffset, 0);
}

static endCxxReferencedDeclWire(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
