// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class CxxTypeInfoWire {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):CxxTypeInfoWire {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsCxxTypeInfoWire(bb:flatbuffers.ByteBuffer, obj?:CxxTypeInfoWire):CxxTypeInfoWire {
  return (obj || new CxxTypeInfoWire()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsCxxTypeInfoWire(bb:flatbuffers.ByteBuffer, obj?:CxxTypeInfoWire):CxxTypeInfoWire {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new CxxTypeInfoWire()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

type():string|null
type(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
type(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

qualType():string|null
qualType(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
qualType(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

desugaredQualType():string|null
desugaredQualType(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
desugaredQualType(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

typeAliasDeclId():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

typeAliasDeclQualifiedName():string|null
typeAliasDeclQualifiedName(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
typeAliasDeclQualifiedName(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startCxxTypeInfoWire(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addType(builder:flatbuffers.Builder, typeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, typeOffset, 0);
}

static addQualType(builder:flatbuffers.Builder, qualTypeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, qualTypeOffset, 0);
}

static addDesugaredQualType(builder:flatbuffers.Builder, desugaredQualTypeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, desugaredQualTypeOffset, 0);
}

static addTypeAliasDeclId(builder:flatbuffers.Builder, typeAliasDeclId:bigint) {
  builder.addFieldInt64(3, typeAliasDeclId, BigInt('0'));
}

static addTypeAliasDeclQualifiedName(builder:flatbuffers.Builder, typeAliasDeclQualifiedNameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, typeAliasDeclQualifiedNameOffset, 0);
}

static endCxxTypeInfoWire(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createCxxTypeInfoWire(builder:flatbuffers.Builder, typeOffset:flatbuffers.Offset, qualTypeOffset:flatbuffers.Offset, desugaredQualTypeOffset:flatbuffers.Offset, typeAliasDeclId:bigint, typeAliasDeclQualifiedNameOffset:flatbuffers.Offset):flatbuffers.Offset {
  CxxTypeInfoWire.startCxxTypeInfoWire(builder);
  CxxTypeInfoWire.addType(builder, typeOffset);
  CxxTypeInfoWire.addQualType(builder, qualTypeOffset);
  CxxTypeInfoWire.addDesugaredQualType(builder, desugaredQualTypeOffset);
  CxxTypeInfoWire.addTypeAliasDeclId(builder, typeAliasDeclId);
  CxxTypeInfoWire.addTypeAliasDeclQualifiedName(builder, typeAliasDeclQualifiedNameOffset);
  return CxxTypeInfoWire.endCxxTypeInfoWire(builder);
}
}
