/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { CxxTypeInfoWire } from '../ark-cxx-ast-fb/cxx-type-info-wire';


export class CxxCtorAnyInitWire {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):CxxCtorAnyInitWire {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsCxxCtorAnyInitWire(bb:flatbuffers.ByteBuffer, obj?:CxxCtorAnyInitWire):CxxCtorAnyInitWire {
  return (obj || new CxxCtorAnyInitWire()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsCxxCtorAnyInitWire(bb:flatbuffers.ByteBuffer, obj?:CxxCtorAnyInitWire):CxxCtorAnyInitWire {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new CxxCtorAnyInitWire()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

kind():string|null
kind(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
kind(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

type(obj?:CxxTypeInfoWire):CxxTypeInfoWire|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new CxxTypeInfoWire()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startCxxCtorAnyInitWire(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addKind(builder:flatbuffers.Builder, kindOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, kindOffset, 0);
}

static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, nameOffset, 0);
}

static addType(builder:flatbuffers.Builder, typeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, typeOffset, 0);
}

static endCxxCtorAnyInitWire(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
