/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { CxxRangeWire } from '../ark-cxx-ast-fb/cxx-range-wire';


export class CxxAliasInfoWire {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):CxxAliasInfoWire {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsCxxAliasInfoWire(bb:flatbuffers.ByteBuffer, obj?:CxxAliasInfoWire):CxxAliasInfoWire {
  return (obj || new CxxAliasInfoWire()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsCxxAliasInfoWire(bb:flatbuffers.ByteBuffer, obj?:CxxAliasInfoWire):CxxAliasInfoWire {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new CxxAliasInfoWire()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

declCode():string|null
declCode(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
declCode(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

range(obj?:CxxRangeWire):CxxRangeWire|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new CxxRangeWire()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startCxxAliasInfoWire(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addDeclCode(builder:flatbuffers.Builder, declCodeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, declCodeOffset, 0);
}

static addRange(builder:flatbuffers.Builder, rangeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, rangeOffset, 0);
}

static endCxxAliasInfoWire(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
