/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { CxxAstNodeWire } from '../ark-cxx-ast-fb/cxx-ast-node-wire';


export class CxxAstPayload {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):CxxAstPayload {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsCxxAstPayload(bb:flatbuffers.ByteBuffer, obj?:CxxAstPayload):CxxAstPayload {
  return (obj || new CxxAstPayload()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsCxxAstPayload(bb:flatbuffers.ByteBuffer, obj?:CxxAstPayload):CxxAstPayload {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new CxxAstPayload()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

wireVersion():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

sourceFile():string|null
sourceFile(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
sourceFile(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

flatPath():string|null
flatPath(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
flatPath(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

root(obj?:CxxAstNodeWire):CxxAstNodeWire|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new CxxAstNodeWire()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startCxxAstPayload(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addWireVersion(builder:flatbuffers.Builder, wireVersion:number) {
  builder.addFieldInt32(0, wireVersion, 0);
}

static addSourceFile(builder:flatbuffers.Builder, sourceFileOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, sourceFileOffset, 0);
}

static addFlatPath(builder:flatbuffers.Builder, flatPathOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, flatPathOffset, 0);
}

static addRoot(builder:flatbuffers.Builder, rootOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, rootOffset, 0);
}

static endCxxAstPayload(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishCxxAstPayloadBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedCxxAstPayloadBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}

}
