// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { CxxTypeInfoWire } from '../ark-cxx-ast-fb/cxx-type-info-wire';


export class DefaultArgWire {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):DefaultArgWire {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsDefaultArgWire(bb:flatbuffers.ByteBuffer, obj?:DefaultArgWire):DefaultArgWire {
  return (obj || new DefaultArgWire()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsDefaultArgWire(bb:flatbuffers.ByteBuffer, obj?:DefaultArgWire):DefaultArgWire {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new DefaultArgWire()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

kind():string|null
kind(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
kind(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

type(obj?:CxxTypeInfoWire):CxxTypeInfoWire|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new CxxTypeInfoWire()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startDefaultArgWire(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addKind(builder:flatbuffers.Builder, kindOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, kindOffset, 0);
}

static addType(builder:flatbuffers.Builder, typeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, typeOffset, 0);
}

static endDefaultArgWire(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
