/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export { ClassBaseWire } from './ark-cxx-ast-fb/class-base-wire';
export { CxxAliasInfoWire } from './ark-cxx-ast-fb/cxx-alias-info-wire';
export { CxxAstNodeWire } from './ark-cxx-ast-fb/cxx-ast-node-wire';
export { CxxAstPayload } from './ark-cxx-ast-fb/cxx-ast-payload';
export { CxxCtorAnyInitWire } from './ark-cxx-ast-fb/cxx-ctor-any-init-wire';
export { CxxEnclosingFunctionWire } from './ark-cxx-ast-fb/cxx-enclosing-function-wire';
export { CxxIncludeInfoWire } from './ark-cxx-ast-fb/cxx-include-info-wire';
export { CxxLocWire } from './ark-cxx-ast-fb/cxx-loc-wire';
export { CxxNominatedNamespaceWire } from './ark-cxx-ast-fb/cxx-nominated-namespace-wire';
export { CxxPositionWire } from './ark-cxx-ast-fb/cxx-position-wire';
export { CxxRangeWire } from './ark-cxx-ast-fb/cxx-range-wire';
export { CxxReferencedDeclWire } from './ark-cxx-ast-fb/cxx-referenced-decl-wire';
export { CxxTypeInfoWire } from './ark-cxx-ast-fb/cxx-type-info-wire';
export { DefaultArgWire } from './ark-cxx-ast-fb/default-arg-wire';
export { DtorTypeWire } from './ark-cxx-ast-fb/dtor-type-wire';
