/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_ASTWIRE_ARKCXXASTFB_H_
#define FLATBUFFERS_GENERATED_ASTWIRE_ARKCXXASTFB_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

namespace ArkCxxAstFb {

struct CxxPositionWire;
struct CxxPositionWireBuilder;

struct CxxRangeWire;
struct CxxRangeWireBuilder;

struct CxxTypeInfoWire;
struct CxxTypeInfoWireBuilder;

struct CxxAliasInfoWire;
struct CxxAliasInfoWireBuilder;

struct CxxReferencedDeclWire;
struct CxxReferencedDeclWireBuilder;

struct CxxCtorAnyInitWire;
struct CxxCtorAnyInitWireBuilder;

struct CxxEnclosingFunctionWire;
struct CxxEnclosingFunctionWireBuilder;

struct CxxNominatedNamespaceWire;
struct CxxNominatedNamespaceWireBuilder;

struct DtorTypeWire;
struct DtorTypeWireBuilder;

struct CxxIncludeInfoWire;
struct CxxIncludeInfoWireBuilder;

struct CxxLocWire;
struct CxxLocWireBuilder;

struct DefaultArgWire;
struct DefaultArgWireBuilder;

struct ClassBaseWire;
struct ClassBaseWireBuilder;

struct CxxAstNodeWire;
struct CxxAstNodeWireBuilder;

struct CxxAstPayload;
struct CxxAstPayloadBuilder;

struct CxxPositionWire FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CxxPositionWireBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_LINE = 4,
    VT_COL = 6,
    VT_OFFSET = 8,
    VT_TOK_LEN = 10,
    VT_FILE = 12
  };
  int32_t line() const {
    return GetField<int32_t>(VT_LINE, 0);
  }
  int32_t col() const {
    return GetField<int32_t>(VT_COL, 0);
  }
  uint32_t offset() const {
    return GetField<uint32_t>(VT_OFFSET, 0);
  }
  uint32_t tok_len() const {
    return GetField<uint32_t>(VT_TOK_LEN, 0);
  }
  const ::flatbuffers::String *file() const {
    return GetPointer<const ::flatbuffers::String *>(VT_FILE);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_LINE, 4) &&
           VerifyField<int32_t>(verifier, VT_COL, 4) &&
           VerifyField<uint32_t>(verifier, VT_OFFSET, 4) &&
           VerifyField<uint32_t>(verifier, VT_TOK_LEN, 4) &&
           VerifyOffset(verifier, VT_FILE) &&
           verifier.VerifyString(file()) &&
           verifier.EndTable();
  }
};

struct CxxPositionWireBuilder {
  typedef CxxPositionWire Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_line(int32_t line) {
    fbb_.AddElement<int32_t>(CxxPositionWire::VT_LINE, line, 0);
  }
  void add_col(int32_t col) {
    fbb_.AddElement<int32_t>(CxxPositionWire::VT_COL, col, 0);
  }
  void add_offset(uint32_t offset) {
    fbb_.AddElement<uint32_t>(CxxPositionWire::VT_OFFSET, offset, 0);
  }
  void add_tok_len(uint32_t tok_len) {
    fbb_.AddElement<uint32_t>(CxxPositionWire::VT_TOK_LEN, tok_len, 0);
  }
  void add_file(::flatbuffers::Offset<::flatbuffers::String> file) {
    fbb_.AddOffset(CxxPositionWire::VT_FILE, file);
  }
  explicit CxxPositionWireBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CxxPositionWire> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CxxPositionWire>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CxxPositionWire> CreateCxxPositionWire(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t line = 0,
    int32_t col = 0,
    uint32_t offset = 0,
    uint32_t tok_len = 0,
    ::flatbuffers::Offset<::flatbuffers::String> file = 0) {
  CxxPositionWireBuilder builder_(_fbb);
  builder_.add_file(file);
  builder_.add_tok_len(tok_len);
  builder_.add_offset(offset);
  builder_.add_col(col);
  builder_.add_line(line);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<CxxPositionWire> CreateCxxPositionWireDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t line = 0,
    int32_t col = 0,
    uint32_t offset = 0,
    uint32_t tok_len = 0,
    const char *file = nullptr) {
  auto file__ = file ? _fbb.CreateString(file) : 0;
  return ArkCxxAstFb::CreateCxxPositionWire(
      _fbb,
      line,
      col,
      offset,
      tok_len,
      file__);
}

struct CxxRangeWire FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CxxRangeWireBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_BEGIN = 4,
    VT_END = 6,
    VT_SPELLING_LOC = 8,
    VT_EXPANSION_LOC = 10
  };
  const ArkCxxAstFb::CxxPositionWire *begin() const {
    return GetPointer<const ArkCxxAstFb::CxxPositionWire *>(VT_BEGIN);
  }
  const ArkCxxAstFb::CxxPositionWire *end() const {
    return GetPointer<const ArkCxxAstFb::CxxPositionWire *>(VT_END);
  }
  const ArkCxxAstFb::CxxPositionWire *spelling_loc() const {
    return GetPointer<const ArkCxxAstFb::CxxPositionWire *>(VT_SPELLING_LOC);
  }
  const ArkCxxAstFb::CxxPositionWire *expansion_loc() const {
    return GetPointer<const ArkCxxAstFb::CxxPositionWire *>(VT_EXPANSION_LOC);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_BEGIN) &&
           verifier.VerifyTable(begin()) &&
           VerifyOffset(verifier, VT_END) &&
           verifier.VerifyTable(end()) &&
           VerifyOffset(verifier, VT_SPELLING_LOC) &&
           verifier.VerifyTable(spelling_loc()) &&
           VerifyOffset(verifier, VT_EXPANSION_LOC) &&
           verifier.VerifyTable(expansion_loc()) &&
           verifier.EndTable();
  }
};

struct CxxRangeWireBuilder {
  typedef CxxRangeWire Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_begin(::flatbuffers::Offset<ArkCxxAstFb::CxxPositionWire> begin) {
    fbb_.AddOffset(CxxRangeWire::VT_BEGIN, begin);
  }
  void add_end(::flatbuffers::Offset<ArkCxxAstFb::CxxPositionWire> end) {
    fbb_.AddOffset(CxxRangeWire::VT_END, end);
  }
  void add_spelling_loc(::flatbuffers::Offset<ArkCxxAstFb::CxxPositionWire> spelling_loc) {
    fbb_.AddOffset(CxxRangeWire::VT_SPELLING_LOC, spelling_loc);
  }
  void add_expansion_loc(::flatbuffers::Offset<ArkCxxAstFb::CxxPositionWire> expansion_loc) {
    fbb_.AddOffset(CxxRangeWire::VT_EXPANSION_LOC, expansion_loc);
  }
  explicit CxxRangeWireBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CxxRangeWire> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CxxRangeWire>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CxxRangeWire> CreateCxxRangeWire(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<ArkCxxAstFb::CxxPositionWire> begin = 0,
    ::flatbuffers::Offset<ArkCxxAstFb::CxxPositionWire> end = 0,
    ::flatbuffers::Offset<ArkCxxAstFb::CxxPositionWire> spelling_loc = 0,
    ::flatbuffers::Offset<ArkCxxAstFb::CxxPositionWire> expansion_loc = 0) {
  CxxRangeWireBuilder builder_(_fbb);
  builder_.add_expansion_loc(expansion_loc);
  builder_.add_spelling_loc(spelling_loc);
  builder_.add_end(end);
  builder_.add_begin(begin);
  return builder_.Finish();
}

struct CxxTypeInfoWire FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CxxTypeInfoWireBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TYPE = 4,
    VT_QUAL_TYPE = 6,
    VT_DESUGARED_QUAL_TYPE = 8,
    VT_TYPE_ALIAS_DECL_ID = 10,
    VT_TYPE_ALIAS_DECL_QUALIFIED_NAME = 12
  };
  const ::flatbuffers::String *type() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TYPE);
  }
  const ::flatbuffers::String *qual_type() const {
    return GetPointer<const ::flatbuffers::String *>(VT_QUAL_TYPE);
  }
  const ::flatbuffers::String *desugared_qual_type() const {
    return GetPointer<const ::flatbuffers::String *>(VT_DESUGARED_QUAL_TYPE);
  }
  uint64_t type_alias_decl_id() const {
    return GetField<uint64_t>(VT_TYPE_ALIAS_DECL_ID, 0);
  }
  const ::flatbuffers::String *type_alias_decl_qualified_name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TYPE_ALIAS_DECL_QUALIFIED_NAME);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_TYPE) &&
           verifier.VerifyString(type()) &&
           VerifyOffset(verifier, VT_QUAL_TYPE) &&
           verifier.VerifyString(qual_type()) &&
           VerifyOffset(verifier, VT_DESUGARED_QUAL_TYPE) &&
           verifier.VerifyString(desugared_qual_type()) &&
           VerifyField<uint64_t>(verifier, VT_TYPE_ALIAS_DECL_ID, 8) &&
           VerifyOffset(verifier, VT_TYPE_ALIAS_DECL_QUALIFIED_NAME) &&
           verifier.VerifyString(type_alias_decl_qualified_name()) &&
           verifier.EndTable();
  }
};

struct CxxTypeInfoWireBuilder {
  typedef CxxTypeInfoWire Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_type(::flatbuffers::Offset<::flatbuffers::String> type) {
    fbb_.AddOffset(CxxTypeInfoWire::VT_TYPE, type);
  }
  void add_qual_type(::flatbuffers::Offset<::flatbuffers::String> qual_type) {
    fbb_.AddOffset(CxxTypeInfoWire::VT_QUAL_TYPE, qual_type);
  }
  void add_desugared_qual_type(::flatbuffers::Offset<::flatbuffers::String> desugared_qual_type) {
    fbb_.AddOffset(CxxTypeInfoWire::VT_DESUGARED_QUAL_TYPE, desugared_qual_type);
  }
  void add_type_alias_decl_id(uint64_t type_alias_decl_id) {
    fbb_.AddElement<uint64_t>(CxxTypeInfoWire::VT_TYPE_ALIAS_DECL_ID, type_alias_decl_id, 0);
  }
  void add_type_alias_decl_qualified_name(::flatbuffers::Offset<::flatbuffers::String> type_alias_decl_qualified_name) {
    fbb_.AddOffset(CxxTypeInfoWire::VT_TYPE_ALIAS_DECL_QUALIFIED_NAME, type_alias_decl_qualified_name);
  }
  explicit CxxTypeInfoWireBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CxxTypeInfoWire> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CxxTypeInfoWire>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CxxTypeInfoWire> CreateCxxTypeInfoWire(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> type = 0,
    ::flatbuffers::Offset<::flatbuffers::String> qual_type = 0,
    ::flatbuffers::Offset<::flatbuffers::String> desugared_qual_type = 0,
    uint64_t type_alias_decl_id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> type_alias_decl_qualified_name = 0) {
  CxxTypeInfoWireBuilder builder_(_fbb);
  builder_.add_type_alias_decl_id(type_alias_decl_id);
  builder_.add_type_alias_decl_qualified_name(type_alias_decl_qualified_name);
  builder_.add_desugared_qual_type(desugared_qual_type);
  builder_.add_qual_type(qual_type);
  builder_.add_type(type);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<CxxTypeInfoWire> CreateCxxTypeInfoWireDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *type = nullptr,
    const char *qual_type = nullptr,
    const char *desugared_qual_type = nullptr,
    uint64_t type_alias_decl_id = 0,
    const char *type_alias_decl_qualified_name = nullptr) {
  auto type__ = type ? _fbb.CreateString(type) : 0;
  auto qual_type__ = qual_type ? _fbb.CreateString(qual_type) : 0;
  auto desugared_qual_type__ = desugared_qual_type ? _fbb.CreateString(desugared_qual_type) : 0;
  auto type_alias_decl_qualified_name__ = type_alias_decl_qualified_name ? _fbb.CreateString(type_alias_decl_qualified_name) : 0;
  return ArkCxxAstFb::CreateCxxTypeInfoWire(
      _fbb,
      type__,
      qual_type__,
      desugared_qual_type__,
      type_alias_decl_id,
      type_alias_decl_qualified_name__);
}

struct CxxAliasInfoWire FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CxxAliasInfoWireBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_DECL_CODE = 4,
    VT_RANGE = 6
  };
  const ::flatbuffers::String *decl_code() const {
    return GetPointer<const ::flatbuffers::String *>(VT_DECL_CODE);
  }
  const ArkCxxAstFb::CxxRangeWire *range() const {
    return GetPointer<const ArkCxxAstFb::CxxRangeWire *>(VT_RANGE);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_DECL_CODE) &&
           verifier.VerifyString(decl_code()) &&
           VerifyOffset(verifier, VT_RANGE) &&
           verifier.VerifyTable(range()) &&
           verifier.EndTable();
  }
};

struct CxxAliasInfoWireBuilder {
  typedef CxxAliasInfoWire Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_decl_code(::flatbuffers::Offset<::flatbuffers::String> decl_code) {
    fbb_.AddOffset(CxxAliasInfoWire::VT_DECL_CODE, decl_code);
  }
  void add_range(::flatbuffers::Offset<ArkCxxAstFb::CxxRangeWire> range) {
    fbb_.AddOffset(CxxAliasInfoWire::VT_RANGE, range);
  }
  explicit CxxAliasInfoWireBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CxxAliasInfoWire> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CxxAliasInfoWire>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CxxAliasInfoWire> CreateCxxAliasInfoWire(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> decl_code = 0,
    ::flatbuffers::Offset<ArkCxxAstFb::CxxRangeWire> range = 0) {
  CxxAliasInfoWireBuilder builder_(_fbb);
  builder_.add_range(range);
  builder_.add_decl_code(decl_code);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<CxxAliasInfoWire> CreateCxxAliasInfoWireDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *decl_code = nullptr,
    ::flatbuffers::Offset<ArkCxxAstFb::CxxRangeWire> range = 0) {
  auto decl_code__ = decl_code ? _fbb.CreateString(decl_code) : 0;
  return ArkCxxAstFb::CreateCxxAliasInfoWire(
      _fbb,
      decl_code__,
      range);
}

struct CxxReferencedDeclWire FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CxxReferencedDeclWireBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_KIND = 4,
    VT_NAME = 6,
    VT_TYPE = 8,
    VT_ALIAS = 10
  };
  const ::flatbuffers::String *kind() const {
    return GetPointer<const ::flatbuffers::String *>(VT_KIND);
  }
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  const ArkCxxAstFb::CxxTypeInfoWire *type() const {
    return GetPointer<const ArkCxxAstFb::CxxTypeInfoWire *>(VT_TYPE);
  }
  const ArkCxxAstFb::CxxAliasInfoWire *alias() const {
    return GetPointer<const ArkCxxAstFb::CxxAliasInfoWire *>(VT_ALIAS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_KIND) &&
           verifier.VerifyString(kind()) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyOffset(verifier, VT_TYPE) &&
           verifier.VerifyTable(type()) &&
           VerifyOffset(verifier, VT_ALIAS) &&
           verifier.VerifyTable(alias()) &&
           verifier.EndTable();
  }
};

struct CxxReferencedDeclWireBuilder {
  typedef CxxReferencedDeclWire Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_kind(::flatbuffers::Offset<::flatbuffers::String> kind) {
    fbb_.AddOffset(CxxReferencedDeclWire::VT_KIND, kind);
  }
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(CxxReferencedDeclWire::VT_NAME, name);
  }
  void add_type(::flatbuffers::Offset<ArkCxxAstFb::CxxTypeInfoWire> type) {
    fbb_.AddOffset(CxxReferencedDeclWire::VT_TYPE, type);
  }
  void add_alias(::flatbuffers::Offset<ArkCxxAstFb::CxxAliasInfoWire> alias) {
    fbb_.AddOffset(CxxReferencedDeclWire::VT_ALIAS, alias);
  }
  explicit CxxReferencedDeclWireBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CxxReferencedDeclWire> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CxxReferencedDeclWire>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CxxReferencedDeclWire> CreateCxxReferencedDeclWire(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> kind = 0,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    ::flatbuffers::Offset<ArkCxxAstFb::CxxTypeInfoWire> type = 0,
    ::flatbuffers::Offset<ArkCxxAstFb::CxxAliasInfoWire> alias = 0) {
  CxxReferencedDeclWireBuilder builder_(_fbb);
  builder_.add_alias(alias);
  builder_.add_type(type);
  builder_.add_name(name);
  builder_.add_kind(kind);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<CxxReferencedDeclWire> CreateCxxReferencedDeclWireDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *kind = nullptr,
    const char *name = nullptr,
    ::flatbuffers::Offset<ArkCxxAstFb::CxxTypeInfoWire> type = 0,
    ::flatbuffers::Offset<ArkCxxAstFb::CxxAliasInfoWire> alias = 0) {
  auto kind__ = kind ? _fbb.CreateString(kind) : 0;
  auto name__ = name ? _fbb.CreateString(name) : 0;
  return ArkCxxAstFb::CreateCxxReferencedDeclWire(
      _fbb,
      kind__,
      name__,
      type,
      alias);
}

struct CxxCtorAnyInitWire FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CxxCtorAnyInitWireBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_KIND = 4,
    VT_NAME = 6,
    VT_TYPE = 8
  };
  const ::flatbuffers::String *kind() const {
    return GetPointer<const ::flatbuffers::String *>(VT_KIND);
  }
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  const ArkCxxAstFb::CxxTypeInfoWire *type() const {
    return GetPointer<const ArkCxxAstFb::CxxTypeInfoWire *>(VT_TYPE);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_KIND) &&
           verifier.VerifyString(kind()) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyOffset(verifier, VT_TYPE) &&
           verifier.VerifyTable(type()) &&
           verifier.EndTable();
  }
};

struct CxxCtorAnyInitWireBuilder {
  typedef CxxCtorAnyInitWire Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_kind(::flatbuffers::Offset<::flatbuffers::String> kind) {
    fbb_.AddOffset(CxxCtorAnyInitWire::VT_KIND, kind);
  }
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(CxxCtorAnyInitWire::VT_NAME, name);
  }
  void add_type(::flatbuffers::Offset<ArkCxxAstFb::CxxTypeInfoWire> type) {
    fbb_.AddOffset(CxxCtorAnyInitWire::VT_TYPE, type);
  }
  explicit CxxCtorAnyInitWireBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CxxCtorAnyInitWire> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CxxCtorAnyInitWire>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CxxCtorAnyInitWire> CreateCxxCtorAnyInitWire(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> kind = 0,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    ::flatbuffers::Offset<ArkCxxAstFb::CxxTypeInfoWire> type = 0) {
  CxxCtorAnyInitWireBuilder builder_(_fbb);
  builder_.add_type(type);
  builder_.add_name(name);
  builder_.add_kind(kind);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<CxxCtorAnyInitWire> CreateCxxCtorAnyInitWireDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *kind = nullptr,
    const char *name = nullptr,
    ::flatbuffers::Offset<ArkCxxAstFb::CxxTypeInfoWire> type = 0) {
  auto kind__ = kind ? _fbb.CreateString(kind) : 0;
  auto name__ = name ? _fbb.CreateString(name) : 0;
  return ArkCxxAstFb::CreateCxxCtorAnyInitWire(
      _fbb,
      kind__,
      name__,
      type);
}

struct CxxEnclosingFunctionWire FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CxxEnclosingFunctionWireBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_KIND = 6,
    VT_NAME = 8,
    VT_RANGE = 10
  };
  uint64_t id() const {
    return GetField<uint64_t>(VT_ID, 0);
  }
  const ::flatbuffers::String *kind() const {
    return GetPointer<const ::flatbuffers::String *>(VT_KIND);
  }
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  const ArkCxxAstFb::CxxRangeWire *range() const {
    return GetPointer<const ArkCxxAstFb::CxxRangeWire *>(VT_RANGE);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_ID, 8) &&
           VerifyOffset(verifier, VT_KIND) &&
           verifier.VerifyString(kind()) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyOffset(verifier, VT_RANGE) &&
           verifier.VerifyTable(range()) &&
           verifier.EndTable();
  }
};

struct CxxEnclosingFunctionWireBuilder {
  typedef CxxEnclosingFunctionWire Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(uint64_t id) {
    fbb_.AddElement<uint64_t>(CxxEnclosingFunctionWire::VT_ID, id, 0);
  }
  void add_kind(::flatbuffers::Offset<::flatbuffers::String> kind) {
    fbb_.AddOffset(CxxEnclosingFunctionWire::VT_KIND, kind);
  }
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(CxxEnclosingFunctionWire::VT_NAME, name);
  }
  void add_range(::flatbuffers::Offset<ArkCxxAstFb::CxxRangeWire> range) {
    fbb_.AddOffset(CxxEnclosingFunctionWire::VT_RANGE, range);
  }
  explicit CxxEnclosingFunctionWireBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CxxEnclosingFunctionWire> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CxxEnclosingFunctionWire>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CxxEnclosingFunctionWire> CreateCxxEnclosingFunctionWire(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> kind = 0,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    ::flatbuffers::Offset<ArkCxxAstFb::CxxRangeWire> range = 0) {
  CxxEnclosingFunctionWireBuilder builder_(_fbb);
  builder_.add_id(id);
  builder_.add_range(range);
  builder_.add_name(name);
  builder_.add_kind(kind);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<CxxEnclosingFunctionWire> CreateCxxEnclosingFunctionWireDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t id = 0,
    const char *kind = nullptr,
    const char *name = nullptr,
    ::flatbuffers::Offset<ArkCxxAstFb::CxxRangeWire> range = 0) {
  auto kind__ = kind ? _fbb.CreateString(kind) : 0;
  auto name__ = name ? _fbb.CreateString(name) : 0;
  return ArkCxxAstFb::CreateCxxEnclosingFunctionWire(
      _fbb,
      id,
      kind__,
      name__,
      range);
}

struct CxxNominatedNamespaceWire FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CxxNominatedNamespaceWireBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_KIND = 6,
    VT_NAME = 8
  };
  const ::flatbuffers::String *id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ID);
  }
  const ::flatbuffers::String *kind() const {
    return GetPointer<const ::flatbuffers::String *>(VT_KIND);
  }
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ID) &&
           verifier.VerifyString(id()) &&
           VerifyOffset(verifier, VT_KIND) &&
           verifier.VerifyString(kind()) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           verifier.EndTable();
  }
};

struct CxxNominatedNamespaceWireBuilder {
  typedef CxxNominatedNamespaceWire Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(::flatbuffers::Offset<::flatbuffers::String> id) {
    fbb_.AddOffset(CxxNominatedNamespaceWire::VT_ID, id);
  }
  void add_kind(::flatbuffers::Offset<::flatbuffers::String> kind) {
    fbb_.AddOffset(CxxNominatedNamespaceWire::VT_KIND, kind);
  }
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(CxxNominatedNamespaceWire::VT_NAME, name);
  }
  explicit CxxNominatedNamespaceWireBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CxxNominatedNamespaceWire> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CxxNominatedNamespaceWire>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CxxNominatedNamespaceWire> CreateCxxNominatedNamespaceWire(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> kind = 0,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0) {
  CxxNominatedNamespaceWireBuilder builder_(_fbb);
  builder_.add_name(name);
  builder_.add_kind(kind);
  builder_.add_id(id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<CxxNominatedNamespaceWire> CreateCxxNominatedNamespaceWireDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *id = nullptr,
    const char *kind = nullptr,
    const char *name = nullptr) {
  auto id__ = id ? _fbb.CreateString(id) : 0;
  auto kind__ = kind ? _fbb.CreateString(kind) : 0;
  auto name__ = name ? _fbb.CreateString(name) : 0;
  return ArkCxxAstFb::CreateCxxNominatedNamespaceWire(
      _fbb,
      id__,
      kind__,
      name__);
}

struct DtorTypeWire FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DtorTypeWireBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_KIND = 6,
    VT_NAME = 8,
    VT_TYPE = 10
  };
  uint64_t id() const {
    return GetField<uint64_t>(VT_ID, 0);
  }
  const ::flatbuffers::String *kind() const {
    return GetPointer<const ::flatbuffers::String *>(VT_KIND);
  }
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  const ArkCxxAstFb::CxxTypeInfoWire *type() const {
    return GetPointer<const ArkCxxAstFb::CxxTypeInfoWire *>(VT_TYPE);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_ID, 8) &&
           VerifyOffset(verifier, VT_KIND) &&
           verifier.VerifyString(kind()) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyOffset(verifier, VT_TYPE) &&
           verifier.VerifyTable(type()) &&
           verifier.EndTable();
  }
};

struct DtorTypeWireBuilder {
  typedef DtorTypeWire Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(uint64_t id) {
    fbb_.AddElement<uint64_t>(DtorTypeWire::VT_ID, id, 0);
  }
  void add_kind(::flatbuffers::Offset<::flatbuffers::String> kind) {
    fbb_.AddOffset(DtorTypeWire::VT_KIND, kind);
  }
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(DtorTypeWire::VT_NAME, name);
  }
  void add_type(::flatbuffers::Offset<ArkCxxAstFb::CxxTypeInfoWire> type) {
    fbb_.AddOffset(DtorTypeWire::VT_TYPE, type);
  }
  explicit DtorTypeWireBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<DtorTypeWire> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<DtorTypeWire>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<DtorTypeWire> CreateDtorTypeWire(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> kind = 0,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    ::flatbuffers::Offset<ArkCxxAstFb::CxxTypeInfoWire> type = 0) {
  DtorTypeWireBuilder builder_(_fbb);
  builder_.add_id(id);
  builder_.add_type(type);
  builder_.add_name(name);
  builder_.add_kind(kind);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<DtorTypeWire> CreateDtorTypeWireDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t id = 0,
    const char *kind = nullptr,
    const char *name = nullptr,
    ::flatbuffers::Offset<ArkCxxAstFb::CxxTypeInfoWire> type = 0) {
  auto kind__ = kind ? _fbb.CreateString(kind) : 0;
  auto name__ = name ? _fbb.CreateString(name) : 0;
  return ArkCxxAstFb::CreateDtorTypeWire(
      _fbb,
      id,
      kind__,
      name__,
      type);
}

struct CxxIncludeInfoWire FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CxxIncludeInfoWireBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CODE = 4,
    VT_FILE_NAME = 6,
    VT_INCLUDE_NAME = 8,
    VT_INCLUDED_FROM = 10,
    VT_IS_ANGLED = 12,
    VT_KIND = 14,
    VT_LOC = 16,
    VT_RELATIVE_PATH = 18,
    VT_SEARCH_PATH = 20
  };
  const ::flatbuffers::String *code() const {
    return GetPointer<const ::flatbuffers::String *>(VT_CODE);
  }
  const ::flatbuffers::String *file_name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_FILE_NAME);
  }
  const ::flatbuffers::String *include_name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_INCLUDE_NAME);
  }
  const ::flatbuffers::String *included_from() const {
    return GetPointer<const ::flatbuffers::String *>(VT_INCLUDED_FROM);
  }
  bool is_angled() const {
    return GetField<uint8_t>(VT_IS_ANGLED, 0) != 0;
  }
  const ::flatbuffers::String *kind() const {
    return GetPointer<const ::flatbuffers::String *>(VT_KIND);
  }
  const ArkCxxAstFb::CxxPositionWire *loc() const {
    return GetPointer<const ArkCxxAstFb::CxxPositionWire *>(VT_LOC);
  }
  const ::flatbuffers::String *relative_path() const {
    return GetPointer<const ::flatbuffers::String *>(VT_RELATIVE_PATH);
  }
  const ::flatbuffers::String *search_path() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SEARCH_PATH);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_CODE) &&
           verifier.VerifyString(code()) &&
           VerifyOffset(verifier, VT_FILE_NAME) &&
           verifier.VerifyString(file_name()) &&
           VerifyOffset(verifier, VT_INCLUDE_NAME) &&
           verifier.VerifyString(include_name()) &&
           VerifyOffset(verifier, VT_INCLUDED_FROM) &&
           verifier.VerifyString(included_from()) &&
           VerifyField<uint8_t>(verifier, VT_IS_ANGLED, 1) &&
           VerifyOffset(verifier, VT_KIND) &&
           verifier.VerifyString(kind()) &&
           VerifyOffset(verifier, VT_LOC) &&
           verifier.VerifyTable(loc()) &&
           VerifyOffset(verifier, VT_RELATIVE_PATH) &&
           verifier.VerifyString(relative_path()) &&
           VerifyOffset(verifier, VT_SEARCH_PATH) &&
           verifier.VerifyString(search_path()) &&
           verifier.EndTable();
  }
};

struct CxxIncludeInfoWireBuilder {
  typedef CxxIncludeInfoWire Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_code(::flatbuffers::Offset<::flatbuffers::String> code) {
    fbb_.AddOffset(CxxIncludeInfoWire::VT_CODE, code);
  }
  void add_file_name(::flatbuffers::Offset<::flatbuffers::String> file_name) {
    fbb_.AddOffset(CxxIncludeInfoWire::VT_FILE_NAME, file_name);
  }
  void add_include_name(::flatbuffers::Offset<::flatbuffers::String> include_name) {
    fbb_.AddOffset(CxxIncludeInfoWire::VT_INCLUDE_NAME, include_name);
  }
  void add_included_from(::flatbuffers::Offset<::flatbuffers::String> included_from) {
    fbb_.AddOffset(CxxIncludeInfoWire::VT_INCLUDED_FROM, included_from);
  }
  void add_is_angled(bool is_angled) {
    fbb_.AddElement<uint8_t>(CxxIncludeInfoWire::VT_IS_ANGLED, static_cast<uint8_t>(is_angled), 0);
  }
  void add_kind(::flatbuffers::Offset<::flatbuffers::String> kind) {
    fbb_.AddOffset(CxxIncludeInfoWire::VT_KIND, kind);
  }
  void add_loc(::flatbuffers::Offset<ArkCxxAstFb::CxxPositionWire> loc) {
    fbb_.AddOffset(CxxIncludeInfoWire::VT_LOC, loc);
  }
  void add_relative_path(::flatbuffers::Offset<::flatbuffers::String> relative_path) {
    fbb_.AddOffset(CxxIncludeInfoWire::VT_RELATIVE_PATH, relative_path);
  }
  void add_search_path(::flatbuffers::Offset<::flatbuffers::String> search_path) {
    fbb_.AddOffset(CxxIncludeInfoWire::VT_SEARCH_PATH, search_path);
  }
  explicit CxxIncludeInfoWireBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CxxIncludeInfoWire> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CxxIncludeInfoWire>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CxxIncludeInfoWire> CreateCxxIncludeInfoWire(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> code = 0,
    ::flatbuffers::Offset<::flatbuffers::String> file_name = 0,
    ::flatbuffers::Offset<::flatbuffers::String> include_name = 0,
    ::flatbuffers::Offset<::flatbuffers::String> included_from = 0,
    bool is_angled = false,
    ::flatbuffers::Offset<::flatbuffers::String> kind = 0,
    ::flatbuffers::Offset<ArkCxxAstFb::CxxPositionWire> loc = 0,
    ::flatbuffers::Offset<::flatbuffers::String> relative_path = 0,
    ::flatbuffers::Offset<::flatbuffers::String> search_path = 0) {
  CxxIncludeInfoWireBuilder builder_(_fbb);
  builder_.add_search_path(search_path);
  builder_.add_relative_path(relative_path);
  builder_.add_loc(loc);
  builder_.add_kind(kind);
  builder_.add_included_from(included_from);
  builder_.add_include_name(include_name);
  builder_.add_file_name(file_name);
  builder_.add_code(code);
  builder_.add_is_angled(is_angled);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<CxxIncludeInfoWire> CreateCxxIncludeInfoWireDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *code = nullptr,
    const char *file_name = nullptr,
    const char *include_name = nullptr,
    const char *included_from = nullptr,
    bool is_angled = false,
    const char *kind = nullptr,
    ::flatbuffers::Offset<ArkCxxAstFb::CxxPositionWire> loc = 0,
    const char *relative_path = nullptr,
    const char *search_path = nullptr) {
  auto code__ = code ? _fbb.CreateString(code) : 0;
  auto file_name__ = file_name ? _fbb.CreateString(file_name) : 0;
  auto include_name__ = include_name ? _fbb.CreateString(include_name) : 0;
  auto included_from__ = included_from ? _fbb.CreateString(included_from) : 0;
  auto kind__ = kind ? _fbb.CreateString(kind) : 0;
  auto relative_path__ = relative_path ? _fbb.CreateString(relative_path) : 0;
  auto search_path__ = search_path ? _fbb.CreateString(search_path) : 0;
  return ArkCxxAstFb::CreateCxxIncludeInfoWire(
      _fbb,
      code__,
      file_name__,
      include_name__,
      included_from__,
      is_angled,
      kind__,
      loc,
      relative_path__,
      search_path__);
}

struct CxxLocWire FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CxxLocWireBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_FILE = 4,
    VT_LINE = 6,
    VT_COL = 8,
    VT_OFFSET = 10,
    VT_TOK_LEN = 12,
    VT_SPELLING_LOC = 14,
    VT_EXPANSION_LOC = 16
  };
  const ::flatbuffers::String *file() const {
    return GetPointer<const ::flatbuffers::String *>(VT_FILE);
  }
  int32_t line() const {
    return GetField<int32_t>(VT_LINE, 0);
  }
  int32_t col() const {
    return GetField<int32_t>(VT_COL, 0);
  }
  uint32_t offset() const {
    return GetField<uint32_t>(VT_OFFSET, 0);
  }
  uint32_t tok_len() const {
    return GetField<uint32_t>(VT_TOK_LEN, 0);
  }
  const ArkCxxAstFb::CxxPositionWire *spelling_loc() const {
    return GetPointer<const ArkCxxAstFb::CxxPositionWire *>(VT_SPELLING_LOC);
  }
  const ArkCxxAstFb::CxxPositionWire *expansion_loc() const {
    return GetPointer<const ArkCxxAstFb::CxxPositionWire *>(VT_EXPANSION_LOC);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_FILE) &&
           verifier.VerifyString(file()) &&
           VerifyField<int32_t>(verifier, VT_LINE, 4) &&
           VerifyField<int32_t>(verifier, VT_COL, 4) &&
           VerifyField<uint32_t>(verifier, VT_OFFSET, 4) &&
           VerifyField<uint32_t>(verifier, VT_TOK_LEN, 4) &&
           VerifyOffset(verifier, VT_SPELLING_LOC) &&
           verifier.VerifyTable(spelling_loc()) &&
           VerifyOffset(verifier, VT_EXPANSION_LOC) &&
           verifier.VerifyTable(expansion_loc()) &&
           verifier.EndTable();
  }
};

struct CxxLocWireBuilder {
  typedef CxxLocWire Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_file(::flatbuffers::Offset<::flatbuffers::String> file) {
    fbb_.AddOffset(CxxLocWire::VT_FILE, file);
  }
  void add_line(int32_t line) {
    fbb_.AddElement<int32_t>(CxxLocWire::VT_LINE, line, 0);
  }
  void add_col(int32_t col) {
    fbb_.AddElement<int32_t>(CxxLocWire::VT_COL, col, 0);
  }
  void add_offset(uint32_t offset) {
    fbb_.AddElement<uint32_t>(CxxLocWire::VT_OFFSET, offset, 0);
  }
  void add_tok_len(uint32_t tok_len) {
    fbb_.AddElement<uint32_t>(CxxLocWire::VT_TOK_LEN, tok_len, 0);
  }
  void add_spelling_loc(::flatbuffers::Offset<ArkCxxAstFb::CxxPositionWire> spelling_loc) {
    fbb_.AddOffset(CxxLocWire::VT_SPELLING_LOC, spelling_loc);
  }
  void add_expansion_loc(::flatbuffers::Offset<ArkCxxAstFb::CxxPositionWire> expansion_loc) {
    fbb_.AddOffset(CxxLocWire::VT_EXPANSION_LOC, expansion_loc);
  }
  explicit CxxLocWireBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CxxLocWire> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CxxLocWire>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CxxLocWire> CreateCxxLocWire(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> file = 0,
    int32_t line = 0,
    int32_t col = 0,
    uint32_t offset = 0,
    uint32_t tok_len = 0,
    ::flatbuffers::Offset<ArkCxxAstFb::CxxPositionWire> spelling_loc = 0,
    ::flatbuffers::Offset<ArkCxxAstFb::CxxPositionWire> expansion_loc = 0) {
  CxxLocWireBuilder builder_(_fbb);
  builder_.add_expansion_loc(expansion_loc);
  builder_.add_spelling_loc(spelling_loc);
  builder_.add_tok_len(tok_len);
  builder_.add_offset(offset);
  builder_.add_col(col);
  builder_.add_line(line);
  builder_.add_file(file);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<CxxLocWire> CreateCxxLocWireDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *file = nullptr,
    int32_t line = 0,
    int32_t col = 0,
    uint32_t offset = 0,
    uint32_t tok_len = 0,
    ::flatbuffers::Offset<ArkCxxAstFb::CxxPositionWire> spelling_loc = 0,
    ::flatbuffers::Offset<ArkCxxAstFb::CxxPositionWire> expansion_loc = 0) {
  auto file__ = file ? _fbb.CreateString(file) : 0;
  return ArkCxxAstFb::CreateCxxLocWire(
      _fbb,
      file__,
      line,
      col,
      offset,
      tok_len,
      spelling_loc,
      expansion_loc);
}

struct DefaultArgWire FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DefaultArgWireBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_KIND = 4,
    VT_TYPE = 6
  };
  const ::flatbuffers::String *kind() const {
    return GetPointer<const ::flatbuffers::String *>(VT_KIND);
  }
  const ArkCxxAstFb::CxxTypeInfoWire *type() const {
    return GetPointer<const ArkCxxAstFb::CxxTypeInfoWire *>(VT_TYPE);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_KIND) &&
           verifier.VerifyString(kind()) &&
           VerifyOffset(verifier, VT_TYPE) &&
           verifier.VerifyTable(type()) &&
           verifier.EndTable();
  }
};

struct DefaultArgWireBuilder {
  typedef DefaultArgWire Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_kind(::flatbuffers::Offset<::flatbuffers::String> kind) {
    fbb_.AddOffset(DefaultArgWire::VT_KIND, kind);
  }
  void add_type(::flatbuffers::Offset<ArkCxxAstFb::CxxTypeInfoWire> type) {
    fbb_.AddOffset(DefaultArgWire::VT_TYPE, type);
  }
  explicit DefaultArgWireBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<DefaultArgWire> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<DefaultArgWire>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<DefaultArgWire> CreateDefaultArgWire(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> kind = 0,
    ::flatbuffers::Offset<ArkCxxAstFb::CxxTypeInfoWire> type = 0) {
  DefaultArgWireBuilder builder_(_fbb);
  builder_.add_type(type);
  builder_.add_kind(kind);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<DefaultArgWire> CreateDefaultArgWireDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *kind = nullptr,
    ::flatbuffers::Offset<ArkCxxAstFb::CxxTypeInfoWire> type = 0) {
  auto kind__ = kind ? _fbb.CreateString(kind) : 0;
  return ArkCxxAstFb::CreateDefaultArgWire(
      _fbb,
      kind__,
      type);
}

struct ClassBaseWire FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ClassBaseWireBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ACCESS = 4,
    VT_TYPE = 6,
    VT_IS_VIRTUAL = 8,
    VT_WRITTEN_ACCESS = 10
  };
  const ::flatbuffers::String *access() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ACCESS);
  }
  const ArkCxxAstFb::CxxTypeInfoWire *type() const {
    return GetPointer<const ArkCxxAstFb::CxxTypeInfoWire *>(VT_TYPE);
  }
  bool is_virtual() const {
    return GetField<uint8_t>(VT_IS_VIRTUAL, 0) != 0;
  }
  const ::flatbuffers::String *written_access() const {
    return GetPointer<const ::flatbuffers::String *>(VT_WRITTEN_ACCESS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ACCESS) &&
           verifier.VerifyString(access()) &&
           VerifyOffset(verifier, VT_TYPE) &&
           verifier.VerifyTable(type()) &&
           VerifyField<uint8_t>(verifier, VT_IS_VIRTUAL, 1) &&
           VerifyOffset(verifier, VT_WRITTEN_ACCESS) &&
           verifier.VerifyString(written_access()) &&
           verifier.EndTable();
  }
};

struct ClassBaseWireBuilder {
  typedef ClassBaseWire Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_access(::flatbuffers::Offset<::flatbuffers::String> access) {
    fbb_.AddOffset(ClassBaseWire::VT_ACCESS, access);
  }
  void add_type(::flatbuffers::Offset<ArkCxxAstFb::CxxTypeInfoWire> type) {
    fbb_.AddOffset(ClassBaseWire::VT_TYPE, type);
  }
  void add_is_virtual(bool is_virtual) {
    fbb_.AddElement<uint8_t>(ClassBaseWire::VT_IS_VIRTUAL, static_cast<uint8_t>(is_virtual), 0);
  }
  void add_written_access(::flatbuffers::Offset<::flatbuffers::String> written_access) {
    fbb_.AddOffset(ClassBaseWire::VT_WRITTEN_ACCESS, written_access);
  }
  explicit ClassBaseWireBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ClassBaseWire> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ClassBaseWire>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ClassBaseWire> CreateClassBaseWire(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> access = 0,
    ::flatbuffers::Offset<ArkCxxAstFb::CxxTypeInfoWire> type = 0,
    bool is_virtual = false,
    ::flatbuffers::Offset<::flatbuffers::String> written_access = 0) {
  ClassBaseWireBuilder builder_(_fbb);
  builder_.add_written_access(written_access);
  builder_.add_type(type);
  builder_.add_access(access);
  builder_.add_is_virtual(is_virtual);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ClassBaseWire> CreateClassBaseWireDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *access = nullptr,
    ::flatbuffers::Offset<ArkCxxAstFb::CxxTypeInfoWire> type = 0,
    bool is_virtual = false,
    const char *written_access = nullptr) {
  auto access__ = access ? _fbb.CreateString(access) : 0;
  auto written_access__ = written_access ? _fbb.CreateString(written_access) : 0;
  return ArkCxxAstFb::CreateClassBaseWire(
      _fbb,
      access__,
      type,
      is_virtual,
      written_access__);
}

/// Per-node attrs as structured columns (inner/header_units are separate wire vectors).
struct CxxAstNodeWire FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CxxAstNodeWireBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_ORIGINAL_ID = 6,
    VT_HAS_IN_CLASS_INITIALIZER = 8,
    VT_KIND = 10,
    VT_NAME = 12,
    VT_CODE = 14,
    VT_TYPE = 16,
    VT_MANGLED_NAME = 18,
    VT_TAG_USED = 20,
    VT_IS_IMPLICIT = 22,
    VT_STORAGE_CLASS = 24,
    VT_ACCESS = 26,
    VT_REFERENCED_DECL = 28,
    VT_VALUE = 30,
    VT_VALUE_CATEGORY = 32,
    VT_CAST_KIND = 34,
    VT_OPCODE = 36,
    VT_OP = 38,
    VT_IS_POSTFIX = 40,
    VT_IS_ARROW = 42,
    VT_IS_ARRAY = 44,
    VT_TRAIT_FUNC = 46,
    VT_TRAIT_ARGS = 48,
    VT_NOEXCEPT_ARG = 50,
    VT_TYPE_ARG = 52,
    VT_ATOMIC_FUNC = 54,
    VT_PSEUDO_DESTRUCTOR_TYPE = 56,
    VT_TARGET_LABEL_ID = 58,
    VT_ANY_INIT = 60,
    VT_BASE_INIT = 62,
    VT_NOMINATED_NAMESPACE = 64,
    VT_LOC = 66,
    VT_RANGE = 68,
    VT_ENCLOSING_FUNCTION = 70,
    VT_DEFAULT_ARG = 72,
    VT_DTOR = 74,
    VT_DEFAULT_ = 76,
    VT_ARRAY_SIZES = 78,
    VT_TYPE_ARGUMENTS = 80,
    VT_INCLUDES = 82,
    VT_BASES = 84,
    VT_INNER = 86,
    VT_HEADER_UNITS = 88
  };
  const ::flatbuffers::String *id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ID);
  }
  const ::flatbuffers::String *original_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ORIGINAL_ID);
  }
  bool has_in_class_initializer() const {
    return GetField<uint8_t>(VT_HAS_IN_CLASS_INITIALIZER, 0) != 0;
  }
  const ::flatbuffers::String *kind() const {
    return GetPointer<const ::flatbuffers::String *>(VT_KIND);
  }
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  const ::flatbuffers::String *code() const {
    return GetPointer<const ::flatbuffers::String *>(VT_CODE);
  }
  const ArkCxxAstFb::CxxTypeInfoWire *type() const {
    return GetPointer<const ArkCxxAstFb::CxxTypeInfoWire *>(VT_TYPE);
  }
  const ::flatbuffers::String *mangled_name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_MANGLED_NAME);
  }
  const ::flatbuffers::String *tag_used() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TAG_USED);
  }
  bool is_implicit() const {
    return GetField<uint8_t>(VT_IS_IMPLICIT, 0) != 0;
  }
  const ::flatbuffers::String *storage_class() const {
    return GetPointer<const ::flatbuffers::String *>(VT_STORAGE_CLASS);
  }
  const ::flatbuffers::String *access() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ACCESS);
  }
  const ArkCxxAstFb::CxxReferencedDeclWire *referenced_decl() const {
    return GetPointer<const ArkCxxAstFb::CxxReferencedDeclWire *>(VT_REFERENCED_DECL);
  }
  const ::flatbuffers::String *value() const {
    return GetPointer<const ::flatbuffers::String *>(VT_VALUE);
  }
  const ::flatbuffers::String *value_category() const {
    return GetPointer<const ::flatbuffers::String *>(VT_VALUE_CATEGORY);
  }
  const ::flatbuffers::String *cast_kind() const {
    return GetPointer<const ::flatbuffers::String *>(VT_CAST_KIND);
  }
  const ::flatbuffers::String *opcode() const {
    return GetPointer<const ::flatbuffers::String *>(VT_OPCODE);
  }
  const ::flatbuffers::String *op() const {
    return GetPointer<const ::flatbuffers::String *>(VT_OP);
  }
  bool is_postfix() const {
    return GetField<uint8_t>(VT_IS_POSTFIX, 0) != 0;
  }
  bool is_arrow() const {
    return GetField<uint8_t>(VT_IS_ARROW, 0) != 0;
  }
  bool is_array() const {
    return GetField<uint8_t>(VT_IS_ARRAY, 0) != 0;
  }
  const ::flatbuffers::String *trait_func() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TRAIT_FUNC);
  }
  const ::flatbuffers::String *trait_args() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TRAIT_ARGS);
  }
  const ::flatbuffers::String *noexcept_arg() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NOEXCEPT_ARG);
  }
  const ArkCxxAstFb::CxxTypeInfoWire *type_arg() const {
    return GetPointer<const ArkCxxAstFb::CxxTypeInfoWire *>(VT_TYPE_ARG);
  }
  const ::flatbuffers::String *atomic_func() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ATOMIC_FUNC);
  }
  const ::flatbuffers::String *pseudo_destructor_type() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PSEUDO_DESTRUCTOR_TYPE);
  }
  int32_t target_label_id() const {
    return GetField<int32_t>(VT_TARGET_LABEL_ID, 0);
  }
  const ArkCxxAstFb::CxxCtorAnyInitWire *any_init() const {
    return GetPointer<const ArkCxxAstFb::CxxCtorAnyInitWire *>(VT_ANY_INIT);
  }
  const ArkCxxAstFb::CxxTypeInfoWire *base_init() const {
    return GetPointer<const ArkCxxAstFb::CxxTypeInfoWire *>(VT_BASE_INIT);
  }
  const ArkCxxAstFb::CxxNominatedNamespaceWire *nominated_namespace() const {
    return GetPointer<const ArkCxxAstFb::CxxNominatedNamespaceWire *>(VT_NOMINATED_NAMESPACE);
  }
  const ArkCxxAstFb::CxxLocWire *loc() const {
    return GetPointer<const ArkCxxAstFb::CxxLocWire *>(VT_LOC);
  }
  const ArkCxxAstFb::CxxRangeWire *range() const {
    return GetPointer<const ArkCxxAstFb::CxxRangeWire *>(VT_RANGE);
  }
  const ArkCxxAstFb::CxxEnclosingFunctionWire *enclosing_function() const {
    return GetPointer<const ArkCxxAstFb::CxxEnclosingFunctionWire *>(VT_ENCLOSING_FUNCTION);
  }
  const ArkCxxAstFb::DefaultArgWire *default_arg() const {
    return GetPointer<const ArkCxxAstFb::DefaultArgWire *>(VT_DEFAULT_ARG);
  }
  const ArkCxxAstFb::DtorTypeWire *dtor() const {
    return GetPointer<const ArkCxxAstFb::DtorTypeWire *>(VT_DTOR);
  }
  const ::flatbuffers::String *default_() const {
    return GetPointer<const ::flatbuffers::String *>(VT_DEFAULT_);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *array_sizes() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *>(VT_ARRAY_SIZES);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *type_arguments() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *>(VT_TYPE_ARGUMENTS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<ArkCxxAstFb::CxxIncludeInfoWire>> *includes() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<ArkCxxAstFb::CxxIncludeInfoWire>> *>(VT_INCLUDES);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<ArkCxxAstFb::ClassBaseWire>> *bases() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<ArkCxxAstFb::ClassBaseWire>> *>(VT_BASES);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<ArkCxxAstFb::CxxAstNodeWire>> *inner() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<ArkCxxAstFb::CxxAstNodeWire>> *>(VT_INNER);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<ArkCxxAstFb::CxxAstNodeWire>> *header_units() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<ArkCxxAstFb::CxxAstNodeWire>> *>(VT_HEADER_UNITS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ID) &&
           verifier.VerifyString(id()) &&
           VerifyOffset(verifier, VT_ORIGINAL_ID) &&
           verifier.VerifyString(original_id()) &&
           VerifyField<uint8_t>(verifier, VT_HAS_IN_CLASS_INITIALIZER, 1) &&
           VerifyOffset(verifier, VT_KIND) &&
           verifier.VerifyString(kind()) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyOffset(verifier, VT_CODE) &&
           verifier.VerifyString(code()) &&
           VerifyOffset(verifier, VT_TYPE) &&
           verifier.VerifyTable(type()) &&
           VerifyOffset(verifier, VT_MANGLED_NAME) &&
           verifier.VerifyString(mangled_name()) &&
           VerifyOffset(verifier, VT_TAG_USED) &&
           verifier.VerifyString(tag_used()) &&
           VerifyField<uint8_t>(verifier, VT_IS_IMPLICIT, 1) &&
           VerifyOffset(verifier, VT_STORAGE_CLASS) &&
           verifier.VerifyString(storage_class()) &&
           VerifyOffset(verifier, VT_ACCESS) &&
           verifier.VerifyString(access()) &&
           VerifyOffset(verifier, VT_REFERENCED_DECL) &&
           verifier.VerifyTable(referenced_decl()) &&
           VerifyOffset(verifier, VT_VALUE) &&
           verifier.VerifyString(value()) &&
           VerifyOffset(verifier, VT_VALUE_CATEGORY) &&
           verifier.VerifyString(value_category()) &&
           VerifyOffset(verifier, VT_CAST_KIND) &&
           verifier.VerifyString(cast_kind()) &&
           VerifyOffset(verifier, VT_OPCODE) &&
           verifier.VerifyString(opcode()) &&
           VerifyOffset(verifier, VT_OP) &&
           verifier.VerifyString(op()) &&
           VerifyField<uint8_t>(verifier, VT_IS_POSTFIX, 1) &&
           VerifyField<uint8_t>(verifier, VT_IS_ARROW, 1) &&
           VerifyField<uint8_t>(verifier, VT_IS_ARRAY, 1) &&
           VerifyOffset(verifier, VT_TRAIT_FUNC) &&
           verifier.VerifyString(trait_func()) &&
           VerifyOffset(verifier, VT_TRAIT_ARGS) &&
           verifier.VerifyString(trait_args()) &&
           VerifyOffset(verifier, VT_NOEXCEPT_ARG) &&
           verifier.VerifyString(noexcept_arg()) &&
           VerifyOffset(verifier, VT_TYPE_ARG) &&
           verifier.VerifyTable(type_arg()) &&
           VerifyOffset(verifier, VT_ATOMIC_FUNC) &&
           verifier.VerifyString(atomic_func()) &&
           VerifyOffset(verifier, VT_PSEUDO_DESTRUCTOR_TYPE) &&
           verifier.VerifyString(pseudo_destructor_type()) &&
           VerifyField<int32_t>(verifier, VT_TARGET_LABEL_ID, 4) &&
           VerifyOffset(verifier, VT_ANY_INIT) &&
           verifier.VerifyTable(any_init()) &&
           VerifyOffset(verifier, VT_BASE_INIT) &&
           verifier.VerifyTable(base_init()) &&
           VerifyOffset(verifier, VT_NOMINATED_NAMESPACE) &&
           verifier.VerifyTable(nominated_namespace()) &&
           VerifyOffset(verifier, VT_LOC) &&
           verifier.VerifyTable(loc()) &&
           VerifyOffset(verifier, VT_RANGE) &&
           verifier.VerifyTable(range()) &&
           VerifyOffset(verifier, VT_ENCLOSING_FUNCTION) &&
           verifier.VerifyTable(enclosing_function()) &&
           VerifyOffset(verifier, VT_DEFAULT_ARG) &&
           verifier.VerifyTable(default_arg()) &&
           VerifyOffset(verifier, VT_DTOR) &&
           verifier.VerifyTable(dtor()) &&
           VerifyOffset(verifier, VT_DEFAULT_) &&
           verifier.VerifyString(default_()) &&
           VerifyOffset(verifier, VT_ARRAY_SIZES) &&
           verifier.VerifyVector(array_sizes()) &&
           verifier.VerifyVectorOfStrings(array_sizes()) &&
           VerifyOffset(verifier, VT_TYPE_ARGUMENTS) &&
           verifier.VerifyVector(type_arguments()) &&
           verifier.VerifyVectorOfStrings(type_arguments()) &&
           VerifyOffset(verifier, VT_INCLUDES) &&
           verifier.VerifyVector(includes()) &&
           verifier.VerifyVectorOfTables(includes()) &&
           VerifyOffset(verifier, VT_BASES) &&
           verifier.VerifyVector(bases()) &&
           verifier.VerifyVectorOfTables(bases()) &&
           VerifyOffset(verifier, VT_INNER) &&
           verifier.VerifyVector(inner()) &&
           verifier.VerifyVectorOfTables(inner()) &&
           VerifyOffset(verifier, VT_HEADER_UNITS) &&
           verifier.VerifyVector(header_units()) &&
           verifier.VerifyVectorOfTables(header_units()) &&
           verifier.EndTable();
  }
};

struct CxxAstNodeWireBuilder {
  typedef CxxAstNodeWire Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(::flatbuffers::Offset<::flatbuffers::String> id) {
    fbb_.AddOffset(CxxAstNodeWire::VT_ID, id);
  }
  void add_original_id(::flatbuffers::Offset<::flatbuffers::String> original_id) {
    fbb_.AddOffset(CxxAstNodeWire::VT_ORIGINAL_ID, original_id);
  }
  void add_has_in_class_initializer(bool has_in_class_initializer) {
    fbb_.AddElement<uint8_t>(CxxAstNodeWire::VT_HAS_IN_CLASS_INITIALIZER, static_cast<uint8_t>(has_in_class_initializer), 0);
  }
  void add_kind(::flatbuffers::Offset<::flatbuffers::String> kind) {
    fbb_.AddOffset(CxxAstNodeWire::VT_KIND, kind);
  }
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(CxxAstNodeWire::VT_NAME, name);
  }
  void add_code(::flatbuffers::Offset<::flatbuffers::String> code) {
    fbb_.AddOffset(CxxAstNodeWire::VT_CODE, code);
  }
  void add_type(::flatbuffers::Offset<ArkCxxAstFb::CxxTypeInfoWire> type) {
    fbb_.AddOffset(CxxAstNodeWire::VT_TYPE, type);
  }
  void add_mangled_name(::flatbuffers::Offset<::flatbuffers::String> mangled_name) {
    fbb_.AddOffset(CxxAstNodeWire::VT_MANGLED_NAME, mangled_name);
  }
  void add_tag_used(::flatbuffers::Offset<::flatbuffers::String> tag_used) {
    fbb_.AddOffset(CxxAstNodeWire::VT_TAG_USED, tag_used);
  }
  void add_is_implicit(bool is_implicit) {
    fbb_.AddElement<uint8_t>(CxxAstNodeWire::VT_IS_IMPLICIT, static_cast<uint8_t>(is_implicit), 0);
  }
  void add_storage_class(::flatbuffers::Offset<::flatbuffers::String> storage_class) {
    fbb_.AddOffset(CxxAstNodeWire::VT_STORAGE_CLASS, storage_class);
  }
  void add_access(::flatbuffers::Offset<::flatbuffers::String> access) {
    fbb_.AddOffset(CxxAstNodeWire::VT_ACCESS, access);
  }
  void add_referenced_decl(::flatbuffers::Offset<ArkCxxAstFb::CxxReferencedDeclWire> referenced_decl) {
    fbb_.AddOffset(CxxAstNodeWire::VT_REFERENCED_DECL, referenced_decl);
  }
  void add_value(::flatbuffers::Offset<::flatbuffers::String> value) {
    fbb_.AddOffset(CxxAstNodeWire::VT_VALUE, value);
  }
  void add_value_category(::flatbuffers::Offset<::flatbuffers::String> value_category) {
    fbb_.AddOffset(CxxAstNodeWire::VT_VALUE_CATEGORY, value_category);
  }
  void add_cast_kind(::flatbuffers::Offset<::flatbuffers::String> cast_kind) {
    fbb_.AddOffset(CxxAstNodeWire::VT_CAST_KIND, cast_kind);
  }
  void add_opcode(::flatbuffers::Offset<::flatbuffers::String> opcode) {
    fbb_.AddOffset(CxxAstNodeWire::VT_OPCODE, opcode);
  }
  void add_op(::flatbuffers::Offset<::flatbuffers::String> op) {
    fbb_.AddOffset(CxxAstNodeWire::VT_OP, op);
  }
  void add_is_postfix(bool is_postfix) {
    fbb_.AddElement<uint8_t>(CxxAstNodeWire::VT_IS_POSTFIX, static_cast<uint8_t>(is_postfix), 0);
  }
  void add_is_arrow(bool is_arrow) {
    fbb_.AddElement<uint8_t>(CxxAstNodeWire::VT_IS_ARROW, static_cast<uint8_t>(is_arrow), 0);
  }
  void add_is_array(bool is_array) {
    fbb_.AddElement<uint8_t>(CxxAstNodeWire::VT_IS_ARRAY, static_cast<uint8_t>(is_array), 0);
  }
  void add_trait_func(::flatbuffers::Offset<::flatbuffers::String> trait_func) {
    fbb_.AddOffset(CxxAstNodeWire::VT_TRAIT_FUNC, trait_func);
  }
  void add_trait_args(::flatbuffers::Offset<::flatbuffers::String> trait_args) {
    fbb_.AddOffset(CxxAstNodeWire::VT_TRAIT_ARGS, trait_args);
  }
  void add_noexcept_arg(::flatbuffers::Offset<::flatbuffers::String> noexcept_arg) {
    fbb_.AddOffset(CxxAstNodeWire::VT_NOEXCEPT_ARG, noexcept_arg);
  }
  void add_type_arg(::flatbuffers::Offset<ArkCxxAstFb::CxxTypeInfoWire> type_arg) {
    fbb_.AddOffset(CxxAstNodeWire::VT_TYPE_ARG, type_arg);
  }
  void add_atomic_func(::flatbuffers::Offset<::flatbuffers::String> atomic_func) {
    fbb_.AddOffset(CxxAstNodeWire::VT_ATOMIC_FUNC, atomic_func);
  }
  void add_pseudo_destructor_type(::flatbuffers::Offset<::flatbuffers::String> pseudo_destructor_type) {
    fbb_.AddOffset(CxxAstNodeWire::VT_PSEUDO_DESTRUCTOR_TYPE, pseudo_destructor_type);
  }
  void add_target_label_id(int32_t target_label_id) {
    fbb_.AddElement<int32_t>(CxxAstNodeWire::VT_TARGET_LABEL_ID, target_label_id, 0);
  }
  void add_any_init(::flatbuffers::Offset<ArkCxxAstFb::CxxCtorAnyInitWire> any_init) {
    fbb_.AddOffset(CxxAstNodeWire::VT_ANY_INIT, any_init);
  }
  void add_base_init(::flatbuffers::Offset<ArkCxxAstFb::CxxTypeInfoWire> base_init) {
    fbb_.AddOffset(CxxAstNodeWire::VT_BASE_INIT, base_init);
  }
  void add_nominated_namespace(::flatbuffers::Offset<ArkCxxAstFb::CxxNominatedNamespaceWire> nominated_namespace) {
    fbb_.AddOffset(CxxAstNodeWire::VT_NOMINATED_NAMESPACE, nominated_namespace);
  }
  void add_loc(::flatbuffers::Offset<ArkCxxAstFb::CxxLocWire> loc) {
    fbb_.AddOffset(CxxAstNodeWire::VT_LOC, loc);
  }
  void add_range(::flatbuffers::Offset<ArkCxxAstFb::CxxRangeWire> range) {
    fbb_.AddOffset(CxxAstNodeWire::VT_RANGE, range);
  }
  void add_enclosing_function(::flatbuffers::Offset<ArkCxxAstFb::CxxEnclosingFunctionWire> enclosing_function) {
    fbb_.AddOffset(CxxAstNodeWire::VT_ENCLOSING_FUNCTION, enclosing_function);
  }
  void add_default_arg(::flatbuffers::Offset<ArkCxxAstFb::DefaultArgWire> default_arg) {
    fbb_.AddOffset(CxxAstNodeWire::VT_DEFAULT_ARG, default_arg);
  }
  void add_dtor(::flatbuffers::Offset<ArkCxxAstFb::DtorTypeWire> dtor) {
    fbb_.AddOffset(CxxAstNodeWire::VT_DTOR, dtor);
  }
  void add_default_(::flatbuffers::Offset<::flatbuffers::String> default_) {
    fbb_.AddOffset(CxxAstNodeWire::VT_DEFAULT_, default_);
  }
  void add_array_sizes(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> array_sizes) {
    fbb_.AddOffset(CxxAstNodeWire::VT_ARRAY_SIZES, array_sizes);
  }
  void add_type_arguments(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> type_arguments) {
    fbb_.AddOffset(CxxAstNodeWire::VT_TYPE_ARGUMENTS, type_arguments);
  }
  void add_includes(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<ArkCxxAstFb::CxxIncludeInfoWire>>> includes) {
    fbb_.AddOffset(CxxAstNodeWire::VT_INCLUDES, includes);
  }
  void add_bases(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<ArkCxxAstFb::ClassBaseWire>>> bases) {
    fbb_.AddOffset(CxxAstNodeWire::VT_BASES, bases);
  }
  void add_inner(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<ArkCxxAstFb::CxxAstNodeWire>>> inner) {
    fbb_.AddOffset(CxxAstNodeWire::VT_INNER, inner);
  }
  void add_header_units(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<ArkCxxAstFb::CxxAstNodeWire>>> header_units) {
    fbb_.AddOffset(CxxAstNodeWire::VT_HEADER_UNITS, header_units);
  }
  explicit CxxAstNodeWireBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CxxAstNodeWire> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CxxAstNodeWire>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CxxAstNodeWire> CreateCxxAstNodeWire(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> original_id = 0,
    bool has_in_class_initializer = false,
    ::flatbuffers::Offset<::flatbuffers::String> kind = 0,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    ::flatbuffers::Offset<::flatbuffers::String> code = 0,
    ::flatbuffers::Offset<ArkCxxAstFb::CxxTypeInfoWire> type = 0,
    ::flatbuffers::Offset<::flatbuffers::String> mangled_name = 0,
    ::flatbuffers::Offset<::flatbuffers::String> tag_used = 0,
    bool is_implicit = false,
    ::flatbuffers::Offset<::flatbuffers::String> storage_class = 0,
    ::flatbuffers::Offset<::flatbuffers::String> access = 0,
    ::flatbuffers::Offset<ArkCxxAstFb::CxxReferencedDeclWire> referenced_decl = 0,
    ::flatbuffers::Offset<::flatbuffers::String> value = 0,
    ::flatbuffers::Offset<::flatbuffers::String> value_category = 0,
    ::flatbuffers::Offset<::flatbuffers::String> cast_kind = 0,
    ::flatbuffers::Offset<::flatbuffers::String> opcode = 0,
    ::flatbuffers::Offset<::flatbuffers::String> op = 0,
    bool is_postfix = false,
    bool is_arrow = false,
    bool is_array = false,
    ::flatbuffers::Offset<::flatbuffers::String> trait_func = 0,
    ::flatbuffers::Offset<::flatbuffers::String> trait_args = 0,
    ::flatbuffers::Offset<::flatbuffers::String> noexcept_arg = 0,
    ::flatbuffers::Offset<ArkCxxAstFb::CxxTypeInfoWire> type_arg = 0,
    ::flatbuffers::Offset<::flatbuffers::String> atomic_func = 0,
    ::flatbuffers::Offset<::flatbuffers::String> pseudo_destructor_type = 0,
    int32_t target_label_id = 0,
    ::flatbuffers::Offset<ArkCxxAstFb::CxxCtorAnyInitWire> any_init = 0,
    ::flatbuffers::Offset<ArkCxxAstFb::CxxTypeInfoWire> base_init = 0,
    ::flatbuffers::Offset<ArkCxxAstFb::CxxNominatedNamespaceWire> nominated_namespace = 0,
    ::flatbuffers::Offset<ArkCxxAstFb::CxxLocWire> loc = 0,
    ::flatbuffers::Offset<ArkCxxAstFb::CxxRangeWire> range = 0,
    ::flatbuffers::Offset<ArkCxxAstFb::CxxEnclosingFunctionWire> enclosing_function = 0,
    ::flatbuffers::Offset<ArkCxxAstFb::DefaultArgWire> default_arg = 0,
    ::flatbuffers::Offset<ArkCxxAstFb::DtorTypeWire> dtor = 0,
    ::flatbuffers::Offset<::flatbuffers::String> default_ = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> array_sizes = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> type_arguments = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<ArkCxxAstFb::CxxIncludeInfoWire>>> includes = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<ArkCxxAstFb::ClassBaseWire>>> bases = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<ArkCxxAstFb::CxxAstNodeWire>>> inner = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<ArkCxxAstFb::CxxAstNodeWire>>> header_units = 0) {
  CxxAstNodeWireBuilder builder_(_fbb);
  builder_.add_header_units(header_units);
  builder_.add_inner(inner);
  builder_.add_bases(bases);
  builder_.add_includes(includes);
  builder_.add_type_arguments(type_arguments);
  builder_.add_array_sizes(array_sizes);
  builder_.add_default_(default_);
  builder_.add_dtor(dtor);
  builder_.add_default_arg(default_arg);
  builder_.add_enclosing_function(enclosing_function);
  builder_.add_range(range);
  builder_.add_loc(loc);
  builder_.add_nominated_namespace(nominated_namespace);
  builder_.add_base_init(base_init);
  builder_.add_any_init(any_init);
  builder_.add_target_label_id(target_label_id);
  builder_.add_pseudo_destructor_type(pseudo_destructor_type);
  builder_.add_atomic_func(atomic_func);
  builder_.add_type_arg(type_arg);
  builder_.add_noexcept_arg(noexcept_arg);
  builder_.add_trait_args(trait_args);
  builder_.add_trait_func(trait_func);
  builder_.add_op(op);
  builder_.add_opcode(opcode);
  builder_.add_cast_kind(cast_kind);
  builder_.add_value_category(value_category);
  builder_.add_value(value);
  builder_.add_referenced_decl(referenced_decl);
  builder_.add_access(access);
  builder_.add_storage_class(storage_class);
  builder_.add_tag_used(tag_used);
  builder_.add_mangled_name(mangled_name);
  builder_.add_type(type);
  builder_.add_code(code);
  builder_.add_name(name);
  builder_.add_kind(kind);
  builder_.add_original_id(original_id);
  builder_.add_id(id);
  builder_.add_is_array(is_array);
  builder_.add_is_arrow(is_arrow);
  builder_.add_is_postfix(is_postfix);
  builder_.add_is_implicit(is_implicit);
  builder_.add_has_in_class_initializer(has_in_class_initializer);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<CxxAstNodeWire> CreateCxxAstNodeWireDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *id = nullptr,
    const char *original_id = nullptr,
    bool has_in_class_initializer = false,
    const char *kind = nullptr,
    const char *name = nullptr,
    const char *code = nullptr,
    ::flatbuffers::Offset<ArkCxxAstFb::CxxTypeInfoWire> type = 0,
    const char *mangled_name = nullptr,
    const char *tag_used = nullptr,
    bool is_implicit = false,
    const char *storage_class = nullptr,
    const char *access = nullptr,
    ::flatbuffers::Offset<ArkCxxAstFb::CxxReferencedDeclWire> referenced_decl = 0,
    const char *value = nullptr,
    const char *value_category = nullptr,
    const char *cast_kind = nullptr,
    const char *opcode = nullptr,
    const char *op = nullptr,
    bool is_postfix = false,
    bool is_arrow = false,
    bool is_array = false,
    const char *trait_func = nullptr,
    const char *trait_args = nullptr,
    const char *noexcept_arg = nullptr,
    ::flatbuffers::Offset<ArkCxxAstFb::CxxTypeInfoWire> type_arg = 0,
    const char *atomic_func = nullptr,
    const char *pseudo_destructor_type = nullptr,
    int32_t target_label_id = 0,
    ::flatbuffers::Offset<ArkCxxAstFb::CxxCtorAnyInitWire> any_init = 0,
    ::flatbuffers::Offset<ArkCxxAstFb::CxxTypeInfoWire> base_init = 0,
    ::flatbuffers::Offset<ArkCxxAstFb::CxxNominatedNamespaceWire> nominated_namespace = 0,
    ::flatbuffers::Offset<ArkCxxAstFb::CxxLocWire> loc = 0,
    ::flatbuffers::Offset<ArkCxxAstFb::CxxRangeWire> range = 0,
    ::flatbuffers::Offset<ArkCxxAstFb::CxxEnclosingFunctionWire> enclosing_function = 0,
    ::flatbuffers::Offset<ArkCxxAstFb::DefaultArgWire> default_arg = 0,
    ::flatbuffers::Offset<ArkCxxAstFb::DtorTypeWire> dtor = 0,
    const char *default_ = nullptr,
    const std::vector<::flatbuffers::Offset<::flatbuffers::String>> *array_sizes = nullptr,
    const std::vector<::flatbuffers::Offset<::flatbuffers::String>> *type_arguments = nullptr,
    const std::vector<::flatbuffers::Offset<ArkCxxAstFb::CxxIncludeInfoWire>> *includes = nullptr,
    const std::vector<::flatbuffers::Offset<ArkCxxAstFb::ClassBaseWire>> *bases = nullptr,
    const std::vector<::flatbuffers::Offset<ArkCxxAstFb::CxxAstNodeWire>> *inner = nullptr,
    const std::vector<::flatbuffers::Offset<ArkCxxAstFb::CxxAstNodeWire>> *header_units = nullptr) {
  auto id__ = id ? _fbb.CreateString(id) : 0;
  auto original_id__ = original_id ? _fbb.CreateString(original_id) : 0;
  auto kind__ = kind ? _fbb.CreateString(kind) : 0;
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto code__ = code ? _fbb.CreateString(code) : 0;
  auto mangled_name__ = mangled_name ? _fbb.CreateString(mangled_name) : 0;
  auto tag_used__ = tag_used ? _fbb.CreateString(tag_used) : 0;
  auto storage_class__ = storage_class ? _fbb.CreateString(storage_class) : 0;
  auto access__ = access ? _fbb.CreateString(access) : 0;
  auto value__ = value ? _fbb.CreateString(value) : 0;
  auto value_category__ = value_category ? _fbb.CreateString(value_category) : 0;
  auto cast_kind__ = cast_kind ? _fbb.CreateString(cast_kind) : 0;
  auto opcode__ = opcode ? _fbb.CreateString(opcode) : 0;
  auto op__ = op ? _fbb.CreateString(op) : 0;
  auto trait_func__ = trait_func ? _fbb.CreateString(trait_func) : 0;
  auto trait_args__ = trait_args ? _fbb.CreateString(trait_args) : 0;
  auto noexcept_arg__ = noexcept_arg ? _fbb.CreateString(noexcept_arg) : 0;
  auto atomic_func__ = atomic_func ? _fbb.CreateString(atomic_func) : 0;
  auto pseudo_destructor_type__ = pseudo_destructor_type ? _fbb.CreateString(pseudo_destructor_type) : 0;
  auto default___ = default_ ? _fbb.CreateString(default_) : 0;
  auto array_sizes__ = array_sizes ? _fbb.CreateVector<::flatbuffers::Offset<::flatbuffers::String>>(*array_sizes) : 0;
  auto type_arguments__ = type_arguments ? _fbb.CreateVector<::flatbuffers::Offset<::flatbuffers::String>>(*type_arguments) : 0;
  auto includes__ = includes ? _fbb.CreateVector<::flatbuffers::Offset<ArkCxxAstFb::CxxIncludeInfoWire>>(*includes) : 0;
  auto bases__ = bases ? _fbb.CreateVector<::flatbuffers::Offset<ArkCxxAstFb::ClassBaseWire>>(*bases) : 0;
  auto inner__ = inner ? _fbb.CreateVector<::flatbuffers::Offset<ArkCxxAstFb::CxxAstNodeWire>>(*inner) : 0;
  auto header_units__ = header_units ? _fbb.CreateVector<::flatbuffers::Offset<ArkCxxAstFb::CxxAstNodeWire>>(*header_units) : 0;
  return ArkCxxAstFb::CreateCxxAstNodeWire(
      _fbb,
      id__,
      original_id__,
      has_in_class_initializer,
      kind__,
      name__,
      code__,
      type,
      mangled_name__,
      tag_used__,
      is_implicit,
      storage_class__,
      access__,
      referenced_decl,
      value__,
      value_category__,
      cast_kind__,
      opcode__,
      op__,
      is_postfix,
      is_arrow,
      is_array,
      trait_func__,
      trait_args__,
      noexcept_arg__,
      type_arg,
      atomic_func__,
      pseudo_destructor_type__,
      target_label_id,
      any_init,
      base_init,
      nominated_namespace,
      loc,
      range,
      enclosing_function,
      default_arg,
      dtor,
      default___,
      array_sizes__,
      type_arguments__,
      includes__,
      bases__,
      inner__,
      header_units__);
}

struct CxxAstPayload FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CxxAstPayloadBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_WIRE_VERSION = 4,
    VT_SOURCE_FILE = 6,
    VT_FLAT_PATH = 8,
    VT_ROOT = 10
  };
  uint32_t wire_version() const {
    return GetField<uint32_t>(VT_WIRE_VERSION, 0);
  }
  const ::flatbuffers::String *source_file() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SOURCE_FILE);
  }
  const ::flatbuffers::String *flat_path() const {
    return GetPointer<const ::flatbuffers::String *>(VT_FLAT_PATH);
  }
  const ArkCxxAstFb::CxxAstNodeWire *root() const {
    return GetPointer<const ArkCxxAstFb::CxxAstNodeWire *>(VT_ROOT);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_WIRE_VERSION, 4) &&
           VerifyOffset(verifier, VT_SOURCE_FILE) &&
           verifier.VerifyString(source_file()) &&
           VerifyOffset(verifier, VT_FLAT_PATH) &&
           verifier.VerifyString(flat_path()) &&
           VerifyOffset(verifier, VT_ROOT) &&
           verifier.VerifyTable(root()) &&
           verifier.EndTable();
  }
};

struct CxxAstPayloadBuilder {
  typedef CxxAstPayload Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_wire_version(uint32_t wire_version) {
    fbb_.AddElement<uint32_t>(CxxAstPayload::VT_WIRE_VERSION, wire_version, 0);
  }
  void add_source_file(::flatbuffers::Offset<::flatbuffers::String> source_file) {
    fbb_.AddOffset(CxxAstPayload::VT_SOURCE_FILE, source_file);
  }
  void add_flat_path(::flatbuffers::Offset<::flatbuffers::String> flat_path) {
    fbb_.AddOffset(CxxAstPayload::VT_FLAT_PATH, flat_path);
  }
  void add_root(::flatbuffers::Offset<ArkCxxAstFb::CxxAstNodeWire> root) {
    fbb_.AddOffset(CxxAstPayload::VT_ROOT, root);
  }
  explicit CxxAstPayloadBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CxxAstPayload> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CxxAstPayload>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CxxAstPayload> CreateCxxAstPayload(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t wire_version = 0,
    ::flatbuffers::Offset<::flatbuffers::String> source_file = 0,
    ::flatbuffers::Offset<::flatbuffers::String> flat_path = 0,
    ::flatbuffers::Offset<ArkCxxAstFb::CxxAstNodeWire> root = 0) {
  CxxAstPayloadBuilder builder_(_fbb);
  builder_.add_root(root);
  builder_.add_flat_path(flat_path);
  builder_.add_source_file(source_file);
  builder_.add_wire_version(wire_version);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<CxxAstPayload> CreateCxxAstPayloadDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t wire_version = 0,
    const char *source_file = nullptr,
    const char *flat_path = nullptr,
    ::flatbuffers::Offset<ArkCxxAstFb::CxxAstNodeWire> root = 0) {
  auto source_file__ = source_file ? _fbb.CreateString(source_file) : 0;
  auto flat_path__ = flat_path ? _fbb.CreateString(flat_path) : 0;
  return ArkCxxAstFb::CreateCxxAstPayload(
      _fbb,
      wire_version,
      source_file__,
      flat_path__,
      root);
}

inline const ArkCxxAstFb::CxxAstPayload *GetCxxAstPayload(const void *buf) {
  return ::flatbuffers::GetRoot<ArkCxxAstFb::CxxAstPayload>(buf);
}

inline const ArkCxxAstFb::CxxAstPayload *GetSizePrefixedCxxAstPayload(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<ArkCxxAstFb::CxxAstPayload>(buf);
}

inline bool VerifyCxxAstPayloadBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<ArkCxxAstFb::CxxAstPayload>(nullptr);
}

inline bool VerifySizePrefixedCxxAstPayloadBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<ArkCxxAstFb::CxxAstPayload>(nullptr);
}

inline void FinishCxxAstPayloadBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<ArkCxxAstFb::CxxAstPayload> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedCxxAstPayloadBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<ArkCxxAstFb::CxxAstPayload> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace ArkCxxAstFb

#endif  // FLATBUFFERS_GENERATED_ASTWIRE_ARKCXXASTFB_H_
